### ISSUE TITLE
User-authored JavaScript found on page (Critical issue)

### ISSUE THREAD

**Issue by jenniejj** [Automattic/amp-wp#752] opened 2017-08-16 07:47 UTC
I’ve recently(starting 08/07/2017) started getting this error in my webmaster console and I currently have 71 errors and still counting.

The google AMP test page shows that is it **NOT a valid AMP page** and don’t know what’s causing this as I didn’t do any recent changes for any of my plugins besides regular updates.

Can someone tell what’s going on and what should I do in order to solve this issue?

I see that my amp pages are getting deindexed from google results so this is critical.

Someof the urls that need attention are:

https://www.hlbenefits.com/cla-safflower-oil-reviews/amp/
https://www.hlbenefits.com/how-know-probiotic-supplements-working/amp/
https://www.hlbenefits.com/best-vegan-and-vegetarian-protein-sources/amp/

**Comment by lkraav** [comment] 2017-08-16 10:26
Yes, same thing. This plugin has started leaving empty `<script></script>` tags since 0.5 release when filtering out incompatible tags. Seems like a bad regex matching issue, but I haven't had time to investigate for details yet.

**Comment by lkraav** [comment] 2017-08-16 14:11
This is probably a duplicate of #747

**Comment by simonrperry** [comment] 2017-08-16 16:33
(I'm not sure it is a dupe @lkraav - this poss related, but different)

We've got 3.7k+ posts now reporting an error. I'm finding the following code being injected by v0.5 plugin. Issue disappeared after rolling back to v0.42

`<script><![CDATA[
	jQuery(".mobile_tel").replaceWith("<a rel='external' href='tel:"+jQuery(".mobile_tel").html()+"'>"+jQuery(".mobile_tel").html()+"");	
]]></script>`

**Comment by mjangda** [comment] 2017-08-16 22:21
Should be fixed in #754.

**Closed** 2017-08-16 22:21 UTC

**Comment by simonrperry** [comment] 2017-08-17 10:16
Just so you know @mjangda, this plugin seemed to be generating the .mobile_tel code block. It doesn't appear on our non-AMP pages.

Good to see action to remove all non-complaint tags as a cover all.

**Comment by betozephyr** [comment] 2018-02-26 16:32
Hello Everyone,
I faced the same issue on my website and it was a little hard for me as I know nothing about AMP. I'm using Godaddy server and I found the website below which helped me to resolve my problem. Issues have dropped 20% since yesterday.

https://www.platopost.com/business/technology/how-to-fix-amp-issue-user-authored-javascript-found-on-page/
