### ISSUE TITLE
It should not be possible for an AMP story author to create blocks created outside of page

### ISSUE THREAD

**Issue by alcurrie** [Automattic/amp-wp#1541] opened 2018-10-30 02:52 UTC
**As a AMP story author, I don’t want be able to create blocks outside of the current page**

 - [ ] _AC 1:_  Ensure that it is not  possible to create blocks created outside of page: https://v.usetapes.com/IYEIsJFz2E. 
     - [ ] _AC 2:_  It should be clear that top inserter is used for creating new blocks only in the current page/layer

**Comment by alcurrie** [comment] 2018-10-30 03:09
@jwold  - I think this was originally your screen cast. I'm not 100% on what the issue/recommendation here is?

**Comment by jwold** [comment] 2018-10-30 16:21
Howdy! The issue is that when I go to insert a new element, it shouldn't be possible for an element to be inserted into the AMP Story, UNLESS it gets dropped into a new page. The video shows an element getting dropped outside of a page, a little orphan all by itself.

We need to change it so that won't happen. This might be a Gutenberg dependency, so I'll let @miina weigh in on that.

**Comment by miina** [comment] 2018-10-30 16:52
@alcurrie and @jwold: Correct, at this moment it's not possible to limit the blocks in Inserter for the root level. See the open issue for Gutenberg: https://github.com/WordPress/gutenberg/issues/7845.

**Comment by miina** [comment] 2018-11-12 14:11
Update:
Checked that at this moment it's still not possible to do this within Gutenberg via code.

Perhaps it would somehow be possible to hide all the other elements from the top Inserter via CSS except for the page. I looked into the source and it looks like the block icons have their block-specific classes in inserter, however, the wrapper (`li` element) does not -- even if we'd hide the inner icon then an empty `li` element would still be there.

@mehigh Perhaps you could double check if you can see any way how to hide the elements except for Page in case of the toolbar Inserter and only in case the Inserter is trying to insert into the very root level? It's very likely that it's not possible, however, just in case would be good to check

If the inserter is not for the root level, for example it's inserting into Vertical Layer like on the screenshot below then leave the Inserter as it is:
![screen shot 2018-11-12 at 11 07 14 am](https://user-images.githubusercontent.com/3294597/48352472-7eeab400-e66b-11e8-8488-70e6acba13f6.png)

If the inserter is for the root level and then hide all the other selectors except for Page block:
![screen shot 2018-11-12 at 11 06 32 am](https://user-images.githubusercontent.com/3294597/48352496-9033c080-e66b-11e8-8f16-d55a78cde101.png)

**Comment by mehigh** [comment] 2018-11-15 14:07
@miina / @alcurrie 
Please review this video I made here: https://dsh.re/a0287
It shows what I was able to achieve with this PR: https://github.com/Automattic/amp-wp/pull/1616

**Comment by mehigh** [comment] 2018-11-19 13:33
What I've done there only went towards limiting the elements that can be added to the root level. It's a hackish solution as the interface isn't yet as intuitive as one could expect. 
It's not ideal, not final. It only improves on the out of the box, but not by enough.

I think it's worth exploring unregistering core block types for the amp stories custom post type - as one can find references of here - https://github.com/WordPress/gutenberg/issues/11723

**Comment by mehigh** [comment] 2018-11-19 13:42
"as your screencast showed some elements that will be changed/no longer appear in the interface" -> when we're talking about the root inserter .. i only showed the "Page" element in there. If you're talking about the other inserters (child inserters) - I haven't touched those at all.

**Comment by miina** [comment] 2018-11-19 13:43
@mehigh The issue with unregistering core block types is that we still need them -- it's just one Inserter in the root level where we don't need the core blocks -- we do need these within the layers though.

One option could be hiding the sections as well -- the Page should theoretically always appear as recently used block since we'll automatically add it when a new AMP Story Post is created. We should test this though, thoughts?

@alcurrie The new interface changes shouldn't influence what's displayed in the root level Inserter so Mike's "hacky" solution might work for now.

**Comment by miina** [comment] 2018-11-19 14:03
@alcurrie Probably we could move this back to In Progress (It was already there but I moved it back to Definition since it seemed to be not possible via Backend solution, looks like there is a way via Frontend).

This ticket shouldn't have any influence on any other tickets and the task here should be defined -- to hide the unnecessary blocks from the Root level Block Inserter (all the other blocks except for Page).

Thoughts?

**Comment by miina** [comment] 2018-11-22 16:52
@alcurrie: Update, it seems to be possible now without CSS; so I'll be resolving this together with #1559.

**Comment by mehigh** [comment] 2018-11-22 21:35
Lovely solution, Miina.
Closing as merged. Passing on to QA.

**Closed by mehigh** 2018-11-22 21:35 UTC
Labels: AMP-Stories, AMP-Stories-Extension, FE

**Comment by alcurrie** [comment] 2018-12-02 14:55
This is confirmed fixed. If a user does not have a page selected, then the only block element that the user can add is a new page block: 
https://cl.ly/063d83576ff3
