### ISSUE TITLE
No hook to insert content after body tag?

### ISSUE THREAD

**Issue by hkchakladar** [Automattic/amp-wp#1177] opened 2018-05-28 18:25 UTC
There is no hook to insert content right after body tag, which is required for using AMP auto ads https://support.google.com/adsense/answer/7334859?hl=en

**Comment by westonruter** [comment] 2018-05-28 18:33
Duplicate of #1143 

Note that you are not _required_ to have this be the first child of the body. It is just recommended:

> The `<amp-auto-ads>` tag should be placed as the first child of the <body>.

https://www.ampproject.org/docs/reference/components/amp-auto-ads

**Closed by westonruter** 2018-05-28 18:33 UTC
