### ISSUE TITLE
Add support for LTS releases in the RuntimeCSS Transformer

### ISSUE THREAD

**Issue by schlessera** [Automattic/amp-wp#4589] opened 2020-04-15 18:40 UTC
## Feature description

LTS releases of the runtime can now be requested from the AMP CDN.

The Optimizer transformer that fetches the AMP runtime CSS to inline should be adapted to support this.

See https://github.com/ampproject/amp-toolbox/commit/b154a73c6dc9231e4060434c562a90d983e2a46d

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* Transformer configuration allows for an LTS runtime version to be requested for inlining the CSS.

## Implementation brief

* Align to the implementation of the NodeJS version: https://github.com/ampproject/amp-toolbox/commit/b154a73c6dc9231e4060434c562a90d983e2a46d

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment] 2020-04-15 19:47
Also mentioned in this PR: https://github.com/ampproject/amp-wp/pull/4403

**Comment by westonruter** [comment] 2020-04-16 22:18
See also perhaps this master issue or LTS and other release channels: #4600.

**Comment by westonruter** [comment] 2020-04-28 16:33
Closing as duplicate of #4600.

**Closed as completed by westonruter** 2020-04-28 16:33 UTC
Labels: Duplicate, Optimizer, WS:Perf
