### ISSUE TITLE
CSS syntax error in tag 'style amp-custom' - bad url for pages which contains Instagram embed contents

### ISSUE THREAD

**Issue by amjad-eremnews** [Automattic/amp-wp#1200] opened 2018-06-06 06:15 UTC
Amp version: 0.7.1. These pages are giving validation errors which has Instagram embeds:

https://www.foochia.com/celebrities/celebrities-news/336516/amp
https://www.foochia.com/celebrities/celebrities-news/293162/amp
https://www.foochia.com/celebrities/celebrities-news/339177/amp

**Comment by westonruter** [comment] 2018-06-06 16:09
I'm not seeing validation errors reported on these URLs:

https://validator.ampproject.org/#url=https%3A%2F%2Fwww.foochia.com%2Fcelebrities%2Fcelebrities-news%2F336516%2Famp
https://validator.ampproject.org/#url=https%3A%2F%2Fwww.foochia.com%2Fcelebrities%2Fcelebrities-news%2F293162%2Famp
https://validator.ampproject.org/#url=https%3A%2F%2Fwww.foochia.com%2Fcelebrities%2Fcelebrities-news%2F339177%2Famp

I believe the issue you are reporting is a duplicate of #1089. You can see workarounds there for the permanent fix (#1164) which is currently scheduled for 1.0.

**Closed by westonruter** 2018-06-06 16:09 UTC
Labels: duplicate
