### ISSUE TITLE
AMP pages broken on WP 6.7.1

### ISSUE THREAD

**Issue by fidoboy** [Automattic/amp-wp#7923] opened 2024-11-27 21:43 UTC
### Bug Description

Since the upgrade to WP 6.7.1 all AMP pages stopped working and now renders without any CSS.

### Expected Behaviour

To have the CSS loaded

### PHP Version

8.3.13

### Plugin Version

2.5.5

### AMP plugin template mode

Transitional

### WordPress Version

6.7.1

**Comment by westonruter** [comment] 2024-11-27 21:50
Please share your Site Health information.

**Comment by westonruter** [comment] 2024-11-27 22:34
Also, it would probably be better to open a new topic on the [support forum](https://wordpress.org/support/plugin/amp/). Please do that, with the Site Health information. We can re-open this issue if it turns out there is a bug in the plugin. My guess is that the latest version of WP increased the amount of CSS which is more than AMP allows. Once you share your Site Health information we'll be able to investigate further.

**Comment by fidoboy** [comment] 2024-11-28 02:18
> Also, it would probably be better to open a new topic on the [support forum](https://wordpress.org/support/plugin/amp/). Please do that, with the Site Health information. We can re-open this issue if it turns out there is a bug in the plugin. My guess is that the latest version of WP increased the amount of CSS which is more than AMP allows. Once you share your Site Health information we'll be able to investigate further.

Nice. This way it looks like the bug doesn't exists.

Oh, I can't post the issue there because they have blocked my account. 

Cheers :)

**Comment by westonruter** [comment] 2024-11-28 03:58
No, that's not why at all. We use the forum to discuss issues before creating them on GitHub.

Share your Site Health information here then.

**Comment by fidoboy** [comment] 2024-11-29 13:39
> No, that's not why at all. We use the forum to discuss issues before creating them on GitHub.
> 
> Share your Site Health information here then.

It doesn't matter to me how you use this issues reporting space in GitHub and I've no account on the support forum, so I can't report it there. I just wanted to help reporting the issue here. And I've done it. So now, if you want to, report it where you wish. I've done my part.

Also, the site health info doesn't provide any info. I've ensured also by installing it on a clean test site and the problem is the same: no CSS being used in any AMP page. It happens only with WP 6.7.1 and not in previous versions. You can check it by yourself doing the same on a clean WP installation. 

I've no relevant errors into the PHP logs, there is no other issue than the AMP pages broken. I'm not using the WP default theme however.

**Comment by milindmore22** [comment] 2024-11-29 14:10
Hello @fidoboy 

From your original description as you mention that AMP pages are rendering without CSS, we are guessing it's because of AMP's CSS limit which is being exceeded because of third-party plugins or theme. To confirm that we need site health information so we can check which theme or plugins you are currently using. 

Here are few steps that might help you debug the issue. 

I would check your CSS budget, because the AMP framework only allows [75 KB CSS on each page](https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/#add-styles-to-a-page), so the AMP plugin adds CSS optimizations, which are sometimes exceeded by third-party plugins or themes.

If you are not sure how to find exceeding CSS budget, follow the below steps:

1) Make sure you have enabled the AMP validation tool
Go-to: Users > Profile > check the checkbox for AMP Development tool > save

2) Visit AMP page exceeding CSS budget check Admin bar for AMP option locate submenu CSS budget and click on it (<a href="https://prnt.sc/18zsc9x">screenshot</a>)

3) Locate the source of excessive CSS (<a href="https://prnt.sc/2005utf">screenshot</a>)

4) If one of the plugins adds excessive CSS find an alternative plugin from the [AMP ecosystem](https://amp-wp.org/ecosystem)

You can learn more about the Reader mode video below:

https://youtu.be/gIBlBhKZ6_k

**Comment by fidoboy** [comment] 2024-11-30 02:48
> Hello @fidoboy
> 
> From your original description as you mention that AMP pages are rendering without CSS, we are guessing it's because of AMP's CSS limit which is being exceeded because of third-party plugins or theme. To confirm that we need site health information so we can check which theme or plugins you are currently using.
> 
> Here are few steps that might help you debug the issue.
> 
> I would check your CSS budget, because the AMP framework only allows [75 KB CSS on each page](https://amp.dev/documentation/guides-and-tutorials/develop/style_and_layout/#add-styles-to-a-page), so the AMP plugin adds CSS optimizations, which are sometimes exceeded by third-party plugins or themes.
> 
> If you are not sure how to find exceeding CSS budget, follow the below steps:
> 
> 1. Make sure you have enabled the AMP validation tool
>    Go-to: Users > Profile > check the checkbox for AMP Development tool > save
> 2. Visit AMP page exceeding CSS budget check Admin bar for AMP option locate submenu CSS budget and click on it ([screenshot](https://prnt.sc/18zsc9x))
> 3. Locate the source of excessive CSS ([screenshot](https://prnt.sc/2005utf))
> 4. If one of the plugins adds excessive CSS find an alternative plugin from the [AMP ecosystem](https://amp-wp.org/ecosystem)
> 
> You can learn more about the Reader mode video below:
> 
> https://youtu.be/gIBlBhKZ6_k

Yes. I know all about this matter but it's not the case. It's not exceding the limits (however I can't see the developer options in toolbar when enabling that on the profile) . And it works fine with all previous WP versions. This happened with WP 6.7.1 and theme being used is TagDiv Newspaper. I hope this helps to replicate the issue. I've ALL plugin deactivated and it happens the same.

PLEASE do the tests by yourself. It doesn't work with the latest WP release. Just doing a WP core rollback on my site, AMP plugin does work again without any issue. So there is some kind of incompatibility between this plugin and the latest WP version. Test it yourself. Try it.

**Comment by fidoboy** [comment] 2024-11-30 15:54
It's not a @support issue. It's a BUG. Please, change the label for this issue

**Comment by westonruter** [comment] 2024-11-30 20:41
I'll note that my own site is in Transitional mode and there is no issue with CSS on the latest version of the plugin and WP core. I'm not using the Newspaper theme, however. It could be a compatibility issue with the theme as well, and not just the plugin or core.

We'll leave the label as-is until we confirm where the bug lies.

**Comment by westonruter** [comment] 2024-11-30 20:41
Sharing your Site Health information will be helpful for us to attempt to replicate the issue.

**Comment by fidoboy** [comment] 2024-11-30 20:57
> I'll note that my own site is in Transitional mode and there is no issue with CSS on the latest version of the plugin and WP core. I'm not using the Newspaper theme, however. It could be a compatibility issue with the theme as well, and not just the plugin or core.
> 
> We'll leave the label as-is until we confirm where the bug lies.

Ok. Confirm it as a bug then. I've done it by using a clean test site with latest WP core and with latest AMP plugin. I've done my tests both with Twetyfive theme and also using TagDiv Newspaper. It failed in both cases. I'm using PHP 8.3.14 if it helps.

**Comment by fidoboy** [comment] 2024-11-30 20:59
Also, using the Twentyfive theme the AMP menu with developer features worked (it doesn't work with Newspaper) and displayed a 47% usage, so it's below the limit.

**Comment by fidoboy** [comment] 2024-11-30 21:01
The same test site, with same setup, as soon as I rollback WP to the 6.6.2 version I have AMP pages working flawlessly. No issues. But as soon as I upgrade to WP 6.7.1 there is the same issue with CSS again.

**Comment by fidoboy** [comment] 2024-11-30 21:06
I can see this AMP info:

```
AMP slug query var	amp
AMP slug defined late	false
AMP mode enabled	transitional
AMP Reader theme	legacy
Plantillas activas	post, page, is_singular
¿Servir todas las plantillas como AMP?	false
Caché transitoria de las hojas de estilos desactivada	false
Umbral de la caché de vigilancia de la hoja de estilos	5000 transients per day
Rango de muestra de la caché de vigilancia de la hoja de estilos	14 days
Número de registros de la caché transitoria de la hoja de estilos	153
Series de tiempo calculadas para la supervisión del almacenamiento en la caché de la hoja de estilo	
20241029: 0
20241031: 0
20241106: 0
20241108: 0
20241109: 0
20241110: 0
20241112: 0
20241113: 0
20241115: 0
20241117: 0
20241122: 0
20241126: 0
20241127: 0
20241130: 153
libxml Version	2.9.1
```

**Comment by westonruter** [comment] 2024-11-30 22:22
> I've done it by using a clean test site with latest WP core and with latest AMP plugin. I've done my tests both with Twetyfive theme and also using TagDiv Newspaper. It failed in both cases. I'm using PHP 8.3.14 if it helps.

I've just created a clean site with the Twenty Twenty-Five theme and the latest version of WP core and the AMP plugin and PHP 8.3. In Transitional mode, there is no problem with the CSS on the AMP pages. 

Non-AMP: https://fruitful-eel-3dcb7a.instawp.xyz/hello-world/
AMP: https://fruitful-eel-3dcb7a.instawp.xyz/hello-world/?amp=1

**Comment by fidoboy** [comment] 2024-12-01 16:31
> > I've done it by using a clean test site with latest WP core and with latest AMP plugin. I've done my tests both with Twetyfive theme and also using TagDiv Newspaper. It failed in both cases. I'm using PHP 8.3.14 if it helps.
> 
> I've just created a clean site with the Twenty Twenty-Five theme and the latest version of WP core and the AMP plugin and PHP 8.3. In Transitional mode, there is no problem with the CSS on the AMP pages.
> 
> Non-AMP: https://fruitful-eel-3dcb7a.instawp.xyz/hello-world/ AMP: https://fruitful-eel-3dcb7a.instawp.xyz/hello-world/?amp=1

Thanks a lot for the verification. It must be another issue then, because it's happening to me on two different sites running on the same server. In both cases, rolling back to previous WP version solves the issue.

**Comment by fidoboy** [comment] 2024-12-01 16:53
I'm going deeper into my tests and I've noticed that when the AMP page is working fine (in WP 6.6.2) there is a amp-loader-0.1.mjs JS file being loaded. There is not any file with that name when it fails (WP 6.7.1). The only difference between two cases is the WP version. Other than this it is all the same. And there is no errors displayed on the browser console in any case.

**Comment by fidoboy** [comment] 2024-12-01 17:13
Another point to take into consideration is that both Twenty-Four and TagDiv Newspaper themes works fine with no issues when rolling back WP core into 6.6.2 version. And both themes are failing when I upgrade into 6.7.1 WP release. I'm using a almost clean test site with very few plugins installed and I've deactivated all of them to the bare minimum to make the tests. Between them, the one failing and the other working, the only difference is the WP version, there is no other. It's on the same server, with all the same (apache, MariaDB, PHP, nginx, redis, etc)

**Comment by milindmore22** [comment] 2024-12-02 07:52
Hi @fidoboy,

We understand that you're encountering an issue with WordPress 6.7.1 and PHP 8.3. 

We've tested this setup on our end using both Twenty Twenty-Four and Newspaper themes by TagDiv, and we haven't encountered any problems.

To narrow down the cause of the issue, please consider sharing your site health information privately using [this form](https://forms.gle/1LktERvMZXkC9u7g9). This will help us identify any specific conflicts or configurations that might be causing the problem.

We're committed to resolving this issue as quickly as possible. Thank you for your patience and cooperation.

**Comment by Zi55550** [comment] 2024-12-05 05:24
> ### وصف الخلل
> منذ الترقية إلى WP 6.7.1 توقفت جميع صفحات AMP عن العمل ويتم عرضها الآن بدون أي CSS.
> 
> ### السلوك المتوقع
> لتحميل CSS
> 
> ### لقطات الشاشة
> _لا يوجد رد_
> 
> ### نسخة PHP
> 8.3.13
> 
> ### إصدار البرنامج الإضافي
> 2.5.5
> 
> ### وضع قالب البرنامج الإضافي AMP
> انتقالي
> 
> ### نسخة ووردبريس
> 6.7.1
> 
> ### صحة الموقع
> _لا يوجد رد_
> 
> ### نسخة جوتنبرج
> _لا يوجد رد_
> 
> ### أنظمة التشغيل المتأثرة
> _لا يوجد رد_
> 
> ### المتصفحات المتأثرة
> _لا يوجد رد_
> 
> ### الأجهزة المتأثرة
> _لا يوجد رد_
> 
> ### معايير القبول
> _لا يوجد رد_
> 
> ### ملخص التنفيذ
> _لا يوجد رد_
> 
> ### تعليمات اختبار ضمان الجودة
> _لا يوجد رد_
> 
> ### العرض التوضيحي
> _لا يوجد رد_
> 
> ### إدخال سجل التغييرات
> _لا يوجد رد_

Git

**Comment by milindmore22** [comment] 2024-12-05 07:59
Hello @fidoboy 

Thank you for sharing the information on your website, We tried to reproduce your site's environment at our end and didn't locate any issues, the site, and AMP pages are working normally as expected.

**Comment by fidoboy** [comment] 2024-12-05 18:42
> Hello @fidoboy
> 
> Thank you for sharing the information on your website, We tried to reproduce your site's environment at our end and didn't locate any issues, the site, and AMP pages are working normally as expected.

Yes, I know. You already [did that before](https://github.com/ampproject/amp-wp/issues/7923#issuecomment-2509403156)  but issue is happening on my side. If you tell me what else can I try I'll do it. As I've said the issue is happening as soon as I update the WP core files without any other change. So there is clearly some changes on this new WP version that are breaking the AMP plugin system.

**Comment by fidoboy** [comment] 2024-12-05 18:46
This same issue is also being [reported here](https://wordpress.org/support/topic/css-style-amp-custom-error/) with no solution other than rolling back to previous WP version.

**Comment by milindmore22** [comment] 2024-12-09 11:07
Hi @fidoboy,

I conducted further testing with the Newspaper theme by 'tagdiv', incorporating the plugins you installed. The initial test was performed with the default theme.

Unfortunately, we haven't been able to reproduce or pinpoint any specific issue that might be causing problems with AMP installation following the WordPress 6.7.1 update.

Given this, I'm marking this issue as resolved for now.

You are welcome to re-open the issue, if you have any additional information to share that might provide more insights.

**Closed as completed by milindmore22** 2024-12-09 11:07 UTC
Labels: Support

**Comment by fidoboy** [comment] 2024-12-12 00:44
After I've updated nginx and redis server to latests versions it seems that it's working again with no further changes. Can't understand what was happening because the only changed thing was WP and I made many tests always with the same results: old WP working fine - new release CSS error with AMP plugin.
