### ISSUE TITLE
Links not parsing without anchor tag

### ISSUE THREAD

**Issue by shivampaw** [Automattic/amp-wp#443] opened 2016-08-22 18:36 UTC
If a post contains a plain link (no anchor text) the link isn't being linked. Example here: https://www.depressionforteens.com/how-to-explain-your-depression/amp/ Above the "Having The Conversation" heading.

**Comment by mjangda** [comment] 2016-08-22 21:57
This doesn't happen in the <a href="https://www.depressionforteens.com/how-to-explain-your-depression/">non-AMP version</a> either.

![autolink](https://cloud.githubusercontent.com/assets/86105/17873120/b9531286-6891-11e6-9887-af2383f2d064.png)

Or am I misunderstanding the issue?

**Comment by shivampaw** [comment] 2016-08-22 22:01
That's weird. I could've sworn it worked fine before. I guess I'll stick with anchor tags. Bug with WordPress?

**Comment by mjangda** [comment] 2016-08-23 04:53
Possibly. I wasn't able to get an auto-link on a local 4.6 install either.

**Comment by silantw** [comment] 2016-11-11 02:20
https://www.guitar.com.tw/guitar-teacher-in-kaohsiung/amp/

The anchor can not be parsed.
This doesn’t happen in the non-AMP version either.
Can the next update be resolved?
Thank you

**Comment by pppdog** [comment] 2016-11-15 10:24
Me Too
```
<a name="#"></a> 
<a id="#"></a> 
```
#566

**Comment by amedina** [comment] 2017-07-04 20:31
Unable to reproduce; closing for now; please re-open if still experiencing the issue.

**Closed by amedina** 2017-07-04 20:31 UTC
