### ISSUE TITLE
Prohibited attributes: align

### ISSUE THREAD

**Issue by laserjobs** [Automattic/amp-wp#278] opened 2016-02-28 15:24 UTC
Old posts using the align attribute are pulling errors in Webmaster Tools. I am going to fix these posts so they do not have it anymore since it is wrong  but I am not sure if this should be stripped anyways in the plugin?

Prohibited attributes: align

Same issue?
https://github.com/Automattic/amp-wp/issues/253

**Comment by mjangda** [comment] 2016-02-29 20:31
Dupe of #253

**Closed by mjangda** 2016-02-29 20:31 UTC
