### ISSUE TITLE
Images on attachment page appear stretched

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1237] opened 2018-07-02 19:29 UTC
In Twenty Seventeen at least, an image on the attachment template looks stretched:

![image](https://user-images.githubusercontent.com/134745/42182514-456e1fc2-7df3-11e8-9537-598739aef71c.png)

```html
<amp-img width="300" height="300" src="https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp-300x300.png" class="attachment-medium size-medium amp-wp-enforced-sizes" alt="" srcset="https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp-300x300.png 300w, https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp-150x150.png 150w, https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp-100x100.png 100w, https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp-270x270.png 270w, https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp-192x192.png 192w, https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp-180x180.png 180w, https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp-32x32.png 32w, https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp.png 512w" sizes="100vw" layout="intrinsic"></amp-img>
```

Non-AMP version:

![image](https://user-images.githubusercontent.com/134745/42182488-32a9e52e-7df3-11e8-95af-477d3ff4c35e.png)

```html
<img width="300" height="300" src="https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp-300x300.png" class="attachment-medium size-medium" alt="" srcset="https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp-300x300.png 300w, https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp-150x150.png 150w, https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp-100x100.png 100w, https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp-270x270.png 270w, https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp-192x192.png 192w, https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp-180x180.png 180w, https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp-32x32.png 32w, https://src.wordpress-develop.test/wp-content/uploads/2018/05/cropped-wordpress-amp.png 512w" sizes="100vw" />
```

**Comment by kienstra** [comment] 2018-07-24 02:18
**Seems Related To Inline Styling**
*But That Might Be Expected*

This looks to only exist when using the `sizes` attribute, like in [Twenty Seventeen](https://github.com/WordPress/wordpress-develop/tree/3aba622692c7a3f41b55a9e63dd5c6df04911cc1/src/wp-content/themes/twentyseventeen).

It looks like the `<amp-img`> adds an inline style of the same width as the `sizes` attribute:

https://paired-ampconfdemo.pantheonsite.io/image-alignment-150x150/?amp
<img width="1425" alt="sizes-attribute" src="https://user-images.githubusercontent.com/4063887/43112742-25b0d3d4-8ebd-11e8-906e-7c505af6f1a3.png">

```html
<amp-img ... sizes="100vw" layout="intrinsic" style="width: 100vw;">
```

In the example above, the `sizes` and `style="width:` values are both `100vw`. When I tried blocking the `sizes` via the plugin's sanitizer, this issue didn't exist. Though I'm not suggesting that as a solution.

Still, maybe the inline styling of `width: 100vw;` is expected.

**Comment by westonruter** [comment] 2018-07-24 23:47
@kienstra @hellofromtonya  I'm sure you've seen this already, but just to make clear that the source of the problem is Twenty Seventeen's `wp_get_attachment_image_attributes` filter:

https://github.com/WordPress/wordpress-develop/blob/ddc8f803c6e99118998191fd2ea24124feb53659/src/wp-content/themes/twentyseventeen/functions.php#L534-L554

That being the case, the solution chosen could perhaps be made part of the `AMP_Core_Theme_Sanitizer` as a specific fix for Twenty Seventeen. 

It could be that the issue here is a fundamental incompatibility between `img` and `amp-img`. In particular, if you set `object-fit:contain` on `img` it works, whereas it does not work with `amp-img`. This is the same problem we faced with getting the header image to work in Twenty Seventeen (see #1074), and the solution for that was to add CSS that targets the `img` inside of the `amp-img`:

https://github.com/Automattic/amp-wp/blob/e3d036c2db60b215636a2b665414b0e599e9ad97/includes/sanitizers/class-amp-core-theme-sanitizer.php#L498-L514

So a similar approach may be needed here. In fact, the existing `add_twentyseventeen_masthead_styles` method there could be renamed `add_twentyseventeen_styles` and this attachment-specific style rule could be put there potentially.

**Comment by kienstra** [comment] 2018-07-25 02:05
Hi @westonruter, 
Thanks, good point that this is coming from the `wp_get_attachment_image_attributes` filter.

Could we wait a little on this issue, to see what happens with [amphtml/17053](https://github.com/ampproject/amphtml/issues/17053)? There's discussion there about possibly changing the `<amp-img>` behavior for `sizes`.

**Comment by westonruter** [comment] 2018-07-25 02:14
Excellent. I'm glad you raised that.

**Comment by hellofromtonya** [comment] 2018-08-06 22:27
@westonruter and @kienstra Upon further investigation, we can remedy the Twenty Seventeen theme's image stretching issue by filtering the attachment image's attributes and changing the following:

1. Set the `layout` attribute to `responsive`.
2. Set the `sizes` attribute to the returned sizes from `wp_get_attachment_image_sizes()`.

IMO these attribute fixes are not a bandaid but rather a fix for how the theme is setting the `sizes` for attachment pages.

**Comment by hellofromtonya** [comment] 2018-08-06 22:47
For reference, PR #1321 fixes this specific issue.  However, since we have an open issue with the AMPHTML project, let's keep this issue open until that one is resolved.  Once resolved, we can come back and validate this issue to ensure there are no regression problems.

**Comment by kienstra** [comment] 2018-09-24 16:46
**Moving To 'Ready For Merging'**

It looks like the [Issue for the AMP project](https://github.com/ampproject/amphtml/issues/17053) probably won't be fixed by this plugin's stable `1.0` release. 

So I'm moving this to 'Ready For Merging' if that's alright, as this already has a merged PR that fixes the issue.

**Comment by kienstra** [comment] 2018-12-04 17:57
**Moving Out Of Milestone**

As this is only tracking https://github.com/ampproject/amphtml/issues/17053, I'm moving this out of the `v1.0` milestone. There's no action needed, other than remove this issue's workaround if that issue is ever resolved.

**Closed** 2018-12-04 22:06 UTC
Labels: [Type] Bug, release

**Comment by westonruter** [comment] 2019-03-29 04:04
This is being revisited in #2036. Please test.
