### ISSUE TITLE
Site scanning performed multiple times on Onboarding Wizard

### ISSUE THREAD

**Issue by dhaval-parekh** [Automattic/amp-wp#6741] opened 2021-11-24 08:23 UTC
### Bug Description

On the "Onboarding Wizard" after selecting template mode, when we go to the next screen we are saving the AMP options. After saving settings, if we go back to the "Site scan" screen. It will rescan the site even though we already scanned the site. 

Since We are forcing standard mode during scanning while on the "Onboarding Wizard".  I assume rescanning site will not provide different data.

While it rescans the site the "Next" button is enabled (while during the first scan it was disabled), So users can go to the next/previous screen while scanning is still running. It will lead the "Site scan" screen to perform the site scanning process multiple times.

https://user-images.githubusercontent.com/8168027/143199998-8b986fd3-ed1b-4a20-8786-688d847030df.mov

### Expected Behaviour

- Since We enforcing the standard mode while scanning the site on "Onboarding Wizard", When the user goes back to the "Site scan" screen we should be rescanning the site.
- While site scanning is in progress, the "Next" and "Previous" buttons should be disabled. That way we should be able to prevent multiple requests of site scanning.

### Plugin Version

2.2.0-alpha

### AMP plugin template mode

Standard, Transitional, Reader

**Comment by milindmore22** [comment] 2021-12-08 14:58
**QA Passed**
Next and Previous button/links are disabled while performing Site Scan.
![image](https://user-images.githubusercontent.com/1132541/145230067-9194211f-b708-4ae0-a3a0-d44492a2cc9f.png)

Going back won't rescan the site, but when the user exists Onboarding Wizard, Settings screen scanner will scan the site for newly selected template mode.

![image](https://user-images.githubusercontent.com/1132541/145230534-7ac132b5-fa31-4105-9077-dddf1bbadcef.png)

**Comment by fellyph** [comment] 2021-12-08 15:59
I was testing other task and saw this behavior:

1. go to reopen wizard
2. go until site scan and let the scan run
3. click on close wizard
4. the test runs another time(is this second scan expected ?)

https://user-images.githubusercontent.com/330792/145240755-86b990ae-b548-40cb-a7ce-f821e2592400.mp4

**Comment by westonruter** [comment] 2021-12-08 19:11
> 4\. the test runs another time(is this second scan expected ?)

Yes: This was added in https://github.com/ampproject/amp-wp/pull/6683 

> > Also, when landing on the AMP Settings screen after completing the Onboarding Wizard, a `scan-if-stale` query parameter is added to the URL. If the scan results are stale, a site scan will be initiated automatically and the query parameter will be removed from the URL.

It needs to re-scan on the Settings screen if not in Standard mode since the scan in the Wizard always uses Standard.

**Comment by milindmore22** [comment] 2021-12-14 13:29
As noticed by Dhaval, our recent changes might have brought back this issue, I am able to reproduce it.

📹  https://recordit.co/r5KGb0xIj7

**Comment by delawski** [comment] 2021-12-14 14:42
I can replicate it as well. Reopening and working on a fix right away.

**Comment by delawski** [comment] 2021-12-15 11:13
~As per https://github.com/ampproject/amp-wp/pull/6791#issuecomment-994634239 and https://github.com/ampproject/amp-wp/pull/6791#pullrequestreview-832644905 QA is complete - moving to QA Passed lane.~

Actually, the PR isn't merged yet. It has 2 approvals so it is ready for merge and final QA.

**Closed as completed** 2021-12-15 14:44 UTC
Labels: Bug, Changelogged, Site Scanning
