### ISSUE TITLE
Code in <pre> elements breaks things

### ISSUE THREAD

**Issue by miken32** [Automattic/amp-wp#613] opened 2017-01-20 23:35 UTC
I have the following in a post:

```
Some plain text.
<pre lang="bash">
#!/bin/bash
tee /tmp/foo<<'EOF'
bar
EOF
</pre>
More plain text.
```

This breaks the resulting AMP HTML; which ends up looking like this:

Some plain text.
```
#!/bin/bash
tee /tmp/foo
More plain text.
```

You can see this demonstrated here: https://mike.eire.ca/2016/07/08/running-freepbx-with-nginx/amp/

**Comment by miken32** [comment] 2017-01-20 23:38
Note I am using the WP-Syntax plugin. I tried disabling it, but it seems to have no bearing on this problem.

**Comment by amedina** [comment] 2017-07-06 01:17
The linked post is validating properly with the <pre> tags.

**Comment by miken32** [comment] 2017-07-06 01:43
This is not about validation. Did you look at the post in AMP and regular versions?

**Comment by amedina** [comment] 2017-07-06 02:44
Oh, I see; I though that the "breaking HTML" was a validation issue. Will look into this in more detail.

**Comment by miken32** [comment] 2017-07-06 04:12
Sorry I didn’t describe it better. Seems like the shell redirect `<<` is treated like an element opening.

**Comment by amedina** [comment] 2017-07-06 21:25
Yeah; something is weird. I spent some time looking at the issue and the '<<' was indeed breaking the HTML as you observed. I switched to work on some theme-related stuff, and when I tried this again it seems to work (see attachment). Looking into it more.

Are you using the plugin version from Github or the one from Wordpress.org?
<img width="577" alt="screen shot 2017-07-06 at 2 21 59 pm" src="https://user-images.githubusercontent.com/506089/27933574-deea6c78-6256-11e7-82a3-5fe23323e254.png">

**Comment by miken32** [comment] 2017-07-06 22:08
I’m installed via Wordpress, but if you give me a patch I’m happy to give it a test if needed.

**Comment by amedina** [comment] 2017-07-06 22:19
A quick check you could do is to download the plugin from GitHub and put it into your plugins directory; change the name of the plugin in amp.php so that it appears as a different plugin. Activate it and check your post. If that works, then the issue is the with the version of in Wordpress.org; we need to address this: https://github.com/Automattic/amp-wp/issues/720

**Comment by amedina** [comment] 2017-08-11 23:48
Plugin has been updated!

**Comment by miken32** [comment] 2017-08-14 15:28
Just updated through Wordpress, still having the same problem. This is on version 0.5.

**Comment by amedina** [comment] 2017-08-14 15:47
Hi @miken32, I am testing a post in that sample `<pre>`-formatted text and it seems to work: https://amptest.wordpress.com/2017/08/14/formatted-text/amp/
I am looking into it to see what else could be happening.

**Comment by miken32** [comment] 2017-08-14 16:05
Well I've confirmed it's not cached by updating the post, and syntax highlighting is still disabled.

[I put up a short test post](https://mike.eire.ca/2017/08/14/testing/amp/) with this content:
```
Some plain text.
<pre lang="bash">
#!/bin/bash
tee /tmp/foo<<'EOF'
bar
EOF
</pre>
More plain text.
```

**Comment by amedina** [comment] 2017-08-14 16:08
Got it; don't know what is happening. Re-opening the issue to track the problem.

**Comment by westonruter** [comment] 2018-03-07 19:37
Without AMP it get's output as:

```html
<div class="wp_syntax" style="position:relative;"><table><tr><td class="code"><pre class="bash" style="font-family:monospace;"><span style="color: #666666; font-style: italic;">#!/bin/bash</span>
<span style="color: #c20cb9; font-weight: bold;">tee</span> <span style="color: #000000; font-weight: bold;">/</span>tmp<span style="color: #000000; font-weight: bold;">/</span>foo<span style="color: #cc0000; font-style: italic;">&lt;&lt;'EOF'
bar
EOF</span></pre></td></tr></table><p class="theCode" style="display:none;">#!/bin/bash
tee /tmp/foo&lt;&lt;'EOF'
bar
EOF</p></div>
```

With AMP active, however, it is output as:

```html
<div class="wp_syntax">
<table><tr><td class="code"><pre class="bash amp-wp-inline-6e55cd5874e142e710268c63a0bf1d5b"><span class="amp-wp-inline-cfd229d4d7837d4ff4f01c73f4645495">#!/bin/bash</span>
<span class="amp-wp-inline-91a3a813b7013bff7d5e41b8b31980af">tee</span> <span class="amp-wp-inline-1e2d3daaad6014ca7a9a9dedd183a25c">/</span>tmp<span class="amp-wp-inline-1e2d3daaad6014ca7a9a9dedd183a25c">/</span>foo<span class="amp-wp-inline-26fd8fecc327ebd0565339da3370cc99">&lt;&lt;'EOF'
bar
EOF</span></pre></td></tr></table>
<p class="theCode">#!/bin/bash
tee /tmp/foo&lt;&lt;'EOF'
bar
EOF</p>
</div>
```

Notice how the `display:none;` is getting stripped out and showing:

![image](https://user-images.githubusercontent.com/134745/37113995-e5eb208e-21fb-11e8-9292-50ca5c74ac74.png)

**Comment by westonruter** [comment] 2018-03-07 20:05
The problem is the use of `safecss_filter_attr()` in https://github.com/Automattic/amp-wp/blob/23eced628815e169ca9831b2ccb460b49adc53c1/includes/sanitizers/class-amp-style-sanitizer.php#L456

This is what is removing the `display` property. It was introduced in https://github.com/Automattic/amp-wp/commit/de2a303563afba4132c317d94324bdfaf793d444 with the comment:

> Filter the styles using `safecss_filter_attr()` to make sure there
> aren't any funky properties. Also alphabetize the valid properties so
> that variable order doesn't cause unnecessary duplication.

The problem is that `safecss_filter_attr()` has a whitelist of the allowed properties, and this is the aspect of the function that needs to be disabled. Fortunately this is trivial to achieve by modifying:

https://github.com/Automattic/amp-wp/blob/23eced628815e169ca9831b2ccb460b49adc53c1/includes/sanitizers/class-amp-style-sanitizer.php#L456

To be like this:

```php
add_filter( 'safe_style_css', '__return_empty_array', PHP_INT_MAX );
$string = safecss_filter_attr( esc_html( $string ) );
remove_filter( 'safe_style_css', '__return_empty_array', PHP_INT_MAX );
```
/cc @coreymckrill

**Comment by westonruter** [comment] 2018-03-07 20:09
@coreymckrill Any objections?

Note that this would obsoleted by #610 and #930.

**Comment by miken32** [comment] 2018-03-07 21:23
My problem has nothing to do with CSS...

**Comment by westonruter** [comment] 2018-03-07 22:08
I was testing specifically in the 0.7-beta version with for a theme that has `amp` theme support, so I'm seeing a different issue than you are. 

If I test in 0.6 with in the existing post templates I do see what you do:

![image](https://user-images.githubusercontent.com/134745/37120444-47d1bed0-220f-11e8-8f27-422ae5916f45.png)

The problem is that `WP_Syntax::beforeFilter()` has a somewhat strange condition in it to not do the replacement if `did_action( 'wp_print_scripts' )` returns `false`. The result is a lack of any syntax highlighting, which I don't think is what you want.

If I change that line to:

```php
if ( did_action( 'wp_print_scripts' ) || ( function_exists( 'is_amp_endpoint' ) && is_amp_endpoint() ) ) {
```

Then it outputs:

![image](https://user-images.githubusercontent.com/134745/37120597-bad639ce-220f-11e8-8db6-10752177e1a7.png)

Here you get styling, but you can see it reproduces the issue I noted above with regard to the `display` property.

So I think there are two fixes: (1) WP Syntax plugin needs to fix the condition for whether to do the parsing, and (2) the AMP plugin needs to fix how it handles the `display` property. 

In regards specifically to `<<` being stripped, I think this is not actually a bug, but is to be expected. The content should be using `&lt;` instead of `<` in the markup. On a HTML5 document if you try validating the above text you get errors:

So it should be:

```html
Some plain text.
<pre lang="bash">
#!/bin/bash
tee /tmp/foo&lt;&lt;'EOF'
bar
EOF
</pre>
More plain text.
```

It may be an accident that `<<` come comes as `<<` in your browser. In other browsers with different HTML parsers it may be interpreted as an `<` tag and be hidden entirely. It should be encoded in the post content so that if the WP Syntax plugin is disabled, or it isn't running (as in the case of AMP here) the content still displays properly but just without styling.

**Comment by miken32** [comment] 2018-03-07 22:15
There is no raw `<<` in my content, as you can see in the HTML output posted above. I think it's in the initial report because GitHub's Markdown parsed `&lt;` to `<`

**Comment by westonruter** [comment] 2018-03-07 22:29
I see raw `<<` in https://github.com/Automattic/amp-wp/issues/613#issuecomment-322232665:

![image](https://user-images.githubusercontent.com/134745/37122045-dd468d2a-2213-11e8-99ae-4cccb102e136.png)

**Comment by westonruter** [comment] 2018-03-07 22:34
If I de-activate the WP Syntax plugin and I enter:

```html
<pre lang="bash">
#!/bin/bash
tee /tmp/foo&lt;&lt;'EOF'
bar
EOF
</pre>
```

Then in AMP and non-AMP alike I see what is expected:

![image](https://user-images.githubusercontent.com/134745/37122217-8508b33a-2214-11e8-87bc-46d6e67bf6b5.png)

**Comment by coreymckrill** [comment] 2018-03-07 22:59
@westonruter Been a long time since I dug into this. What would be the security implications of not running inline style declarations through a safelist? It seems like that could lead to arbitrary strings being output in a style block. Could the bug be fixed by adding more allowed attributes instead of causing it to skip the process entirely?

**Comment by miken32** [comment] 2018-03-07 23:07
Yeah there is a raw `<` in the post; if I put in `&lt;` into the post then AMP works, but the regular post shows the entity. :|

**Comment by coreymckrill** [comment] 2018-03-08 19:52
@westonruter Ah, ok. No objections, then. 👍

**Closed** 2018-03-09 18:14 UTC
