### ISSUE TITLE
The upgraded AMP Plugin from last week is negatively affecting site ranking - it blocks Alexa code which is the site header. Ale can no longer read the AMP pages. Most likely there are other codes residing in the header affected. PLEASE HELP FIX THIS

### ISSUE THREAD

**Issue by schikanza** [Automattic/amp-wp#5605] opened 2020-11-16 21:02 UTC
## Additional context

 - WordPress version:
 - Plugin version:
 - Gutenberg plugin version (if applicable):
 - AMP plugin template mode:
 - PHP version:
 - OS:
 - Browser: [e.g. chrome, safari]

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment] 2020-11-17 04:12
Closing as duplicate of #5606

**Closed as completed by westonruter** 2020-11-17 04:12 UTC
Labels: Duplicate, Support
