### ISSUE TITLE
Wizard Step: Plugin compatibility scanning

### ISSUE THREAD

**Issue by jwold** [Automattic/amp-wp#4719] opened 2020-05-13 22:21 UTC
## Feature description

As part of the onboarding the AMP plugin will check for plugin compatibility compatibility issues, and recommend actions based on what it finds.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* User is made aware of the plugins which cause AMP validation errors. 
* User can easily suppress the plugins that are causing AMP validation errors.
* User is recommended to use Reader mode or Transitional mode when errors from plugins are detected.

## Implementation brief

cf. #4795

1. Add a new Onboarding Wizard step for Site Scanning as well as an area on the Settings Screen to initiate a scan.
1. Obtain validation results for URLs representative of the site. See IB on #4795.
1. On the Template mode selection, do not recommend Standard mode if there are any validation errors detected.
1. Add an onboarding screen for Plugins that lists out the plugins which are causing problems and provide option to suppress each.

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment] 2020-05-15 19:38
This step is not going to be about plugin compatibility scanning only. It will also check for the theme compatibility. If a theme is generating AMP validation errors, then this will be a signal for which template mode will be recommended to the user. For example:

* If there are no errors caused by the theme or plugins, then we could recommend Standard mode.
* If there are no errors caused by the theme but there are errors caused by plugins, we could recommend Transitional mode, along with suggesting for the offending plugins to be turned off in AMP responses.
* If there are errors caused by both the theme and plugins, then we can recommend Reader mode along with the plugin suppression suggestion.

See #4795.

> If it finds incompatible plugins it will show list of plugins that are causing problems, and ask user if they want to turn off the plugins.

Turn them off specifically when generating AMP pages.

**Comment by jwold** [comment] 2020-07-07 15:43
What about scenarios where there are theme errors, but no plugin errors?

**Comment by jwold** [comment] 2020-07-07 15:50
![My Sketches - 2020-07-07 08 20 49](https://user-images.githubusercontent.com/3411173/86807562-d4d55200-c02e-11ea-8847-8a89d430d8c9.jpg)

**Comment by westonruter** [comment] 2020-07-08 04:03
Yes, if there are theme errors, then we recommend Reader mode.

If there are no theme errors but there are plugin errors, then Transitional mode can recommended (especially for technical users).

If there are no theme errors nor plugin errors, then Standard mode can be recommended (especially for technical users). 

I believe the scenarios are captured in the [AMP Copy Configuration Table](https://docs.google.com/document/d/1yjpVpGV6PCPs641hzmUWXzo0a46VKvjiWTytFqxtyEk/edit#heading=h.gzizthhiwjrc) doc.

**Comment by westonruter** [comment] 2020-07-29 16:56
Note we'll need to incorporate site scanning into the settings screen as well.

This should make the recommendations consistent between the wizard and settings screen. See https://github.com/ampproject/amp-wp/issues/4990#issuecomment-659645972.

**Comment by westonruter** [comment] 2020-08-05 22:47
There needs to be a button on the Settings screen to initiate a re-scan.

**Comment by westonruter** [comment] 2020-08-05 22:48
Also, with #1756 when using WP-Cron, we'll want to provide a summary of the most recent site scan results when the user first lands on the Settings screen. Then they can re-scan if they want to get more up-to-date results.

**Comment by johnwatkins0** [comment] 2020-08-11 23:02
Using this task as the jumping-off point for the various site scanning tasks. I kinda think https://github.com/ampproject/amp-wp/issues/4795 can be closed in favor of this one, but I'll hold off for now.

**Comment by johnwatkins0** [comment] 2020-08-11 23:04
@jwold Assigning this to you alongside myself for the design aspects. It'll probably be some days before I start on building the UI for this, but I think I'll be there in within 1-2 weeks.

**Comment by westonruter** [comment] 2020-08-11 23:32
In addition to showing the most recent Site Scan results on the Settings screen and providing the ability to trigger a scan from there, there's an opportunity here for integration with Plugin Suppression. So in the Wizard for example, after the site scan has completed, there should be a screen that shows the site scan results, and when there are plugins causing validation errors, provide a way to easily suppress them from AMP responses at that point. This will make Plugin Suppression part of the onboarding flow, whereas currently it is relegated to the Advanced section. The onboarding wizard should take the site scan results to suggest which template mode is best based on the site scan results, but then also which plugins should be suppressed based on the site scan results. Eventually we could also suggest alternatives for plugins that are AMP-compatible.

**Comment by westonruter** [comment] 2020-08-16 20:20
> I kinda think #4795 can be closed in favor of this one, but I'll hold off for now.

Actually, there is one key piece that is distinct for that issue. See https://github.com/ampproject/amp-wp/issues/4795#issuecomment-674573018.

**Comment by westonruter** [comment] 2020-08-22 03:07
I just realized another aspect of plugin scanning which will be important. In the same way we will do for themes in #4795, we need to check which post types, shortcodes, blocks, etc which are registered by each plugin. We can determine this by making a request to some REST API endpoint that lists those entities along with a query var that allows us to force all plugins other than the one supplied in a query var to be suppressed. We can then infer what entities are introduced by each plugin. This information will be critical to present to the user when we suggest plugins for suppression or when we list plugins on the Plugin Suppression table. Users need to know what side effects there will be for suppressing a plugin as much as possible.

**Comment by jwold** [comment] 2021-07-19 20:53
**Notes from a recent team call:**

At the end of the site scanning, we should have a message: "Please verify that everything is correct." 

Site Scanning could then report findings in a user friendly way, and essentially do the Site Review for the user (deprecating #6071 when complete), and have a message, "Some parts of your site may or may not be available, please verify."

So for 2.2 we'll launch the `Review` Section, and for 2.3 (or later) we'll hook into site scanning to help users with the review. This could be done async, so users get a notification later, when the site scanning site review is ready.

**Comment by jwold** [comment] 2021-07-30 20:52
@westonruter a few questions have come up in terms of site scanning:

1. Do we have a sense of how long a site scan can take; in terms of the typical range? 

2. What data will we want to reveal from the site scan in the onboarding wizard/settings? Assuming something like: 
- Theme name, description of error found, number of error(s) found
- Plugin name, description of error(s) found, number of error(s) found, suppress button

3. In 2.2 of AMP plugin we'll offer suppression of plugins. Will we also offer recommendation of better plugin options, or is that a later release? 

cc @schlessera

**Comment by westonruter** [comment] 2021-07-30 23:19
> 1. Do we have a sense of how long a site scan can take; in terms of the typical range?

When running `wp amp validation run --limit=1` from the command line, it obtains one URL of each template and post type. These URLs are obtained via `\AmpProject\AmpWP\Validation\ScannableURLProvider::get_urls()`. On my test site, these include 8 URLs:

1. `post`
1. `page`
1. `attachment`
1. `category`
1. `post_tag`
1. `author`
1. `date`
1. `search`

(Aside: I see this is missing an explicit check of the `page_on_front` and the `page_for_posts`, which will need to be fixed.)

When running that command, checking those 8 URLs takes about 10 seconds. I'm running this inside of a Docker container on a Mac VM, so it's not the fastest either.

I also ran this on amp-wp.org which hast more post types so it results in 23 URLs to check. This took 53 seconds to complete on that environment.

So expecting that scanning will take 30 seconds is reasonable, with the possibility it could take twice as long (or even longer on shared servers), or much less time (on sites with a lot of server resources).

> 2\. What data will we want to reveal from the site scan in the onboarding wizard/settings? Assuming something like:
> 
> * Theme name, description of error found, number of error(s) found
> * Plugin name, description of error(s) found, number of error(s) found, suppress button

Descriptions of the errors found are probably too much information to include here. In other words, the information presented in the AMP Validation sidebar in the post editor is probably excessive. At the most there could be link to the Validated URL screen(s) to get the details if the user wants it. 

So yeah, I think in this context we'd primarily list out the theme/plugins that are causing issues. Providing a count of the number of issues each theme/plugin causes could be useful as well. Linking to the results on Validated URL screens would be a further step, but I can't envision how do this in a seamless user-friendly way. Maybe I lack imagination.

Including a button to suppress the plugin may be too much for that screen. It may make more sense to include this on a another new Onboarding Wizard step that is presented to users who decide to go with Transitional/Reader template mode when there are plugin errors present. This could embed the same Plugin Suppression table that we have on the settings screen now. The only issue is that users may not know whether to suppress a plugin or not. They may need to finish the wizard to be able to try suppressing a plugin, and then going to a page to see the effect. In that way, it may make even more sense as part of a revamped Dev Tools which allows a user to preview markup being removed and plugins being suppressed in a split-screen UI with the controls on one side and the preview on the other.

> 3. In 2.2 of AMP plugin we'll offer suppression of plugins. Will we also offer recommendation of better plugin options, or is that a later release?

Recommendations of alternative plugins will have to come later once we have a categorization of plugins in a database we can query.

**Comment by jwold** [comment] 2021-08-25 21:45
@delawski here are the latest designs for Site Scanning ready for engineering review. cc @amedina and @westonruter, as there may be some minor copy changes. 

We've had some followup discussions with the team, and wanted to drop an update. This will technically encompass #4795 as well as this ticket, as the scan results are revealed on the same page. If I need to break up the features let me know. Also, the work here is related to #6071, so it's probably important to pick them up in concern. 

**1. Site scan step A**

In the onboarding wizard we'll have a new step, the site scan. This will happen right after the technical background question, and can begin as soon as the user enters the onboarding wizard. Once they appear on the site scan page, they'll be presented with a UI showing the scan in progress. The `Next` step will be grayed out until the scan completes. 

![Site scan](https://user-images.githubusercontent.com/3411173/130868280-bcb149b8-f63a-4044-a818-4d0cb66045cf.png)

**2. Site scan step B**

With the scan complete, the user will see a scan results. If there are no errors found, they will be presented with the following screen:

![Site scan](https://user-images.githubusercontent.com/3411173/130868456-e1eaae5d-b9b3-4633-a32b-06ad54253e1f.png)

If errors are found, they will see the following:

![Site scan](https://user-images.githubusercontent.com/3411173/130868505-a9d4f18b-5c8c-4c2e-b28e-a164871120d4.png)

**3. Template mode updates**

The template mode recommendations will now be updated based on the site scan. Following is an example screenshot of what these updates could look like from the first row in the Config table: https://docs.google.com/document/d/1yjpVpGV6PCPs641hzmUWXzo0a46VKvjiWTytFqxtyEk/edit.

![Template modes](https://user-images.githubusercontent.com/3411173/130868730-5e2dfac8-146d-4a09-b84e-7b596d358bd7.png)

**4. Settings**

Site scan can also be run from the settings screen. Example screenshot:

![Settings](https://user-images.githubusercontent.com/3411173/130868771-8a116ac4-fa3c-45ea-8bb2-14018a5e77c5.png)

Happy to jump on a call or discuss these suggested changes in more detail. Thank you! 

Figma link: https://www.figma.com/file/SfMlDvHc5KHxJmAZN12PIM/?node-id=0%3A1

**Comment by westonruter** [comment] 2021-08-27 18:08
> If errors are found, they will see the following:

Plugin icons are only available in the context of the directory. Icons are not distributed with plugins. So we'll have to show plugins in a list form rather than in card form. Perhaps the Plugin Suppression list table would be relevant in this context, except we wouldn't necessarily be including the UI to suppress the plugin (unless if the user is technical?), and we wouldn't be listing plugins that don't have detected errors. Note how this UI also includes a list of the encountered errors:

![image](https://user-images.githubusercontent.com/134745/131169643-7ff2161b-90e1-4c06-b3bc-4aed340f9858.png)

Also, I recall we talked about having the list of themes/plugins included on the Template mode selection screen instead of (or in addition to) being shown on the site scan results. It probably is good to keep the results on the site scan screen (as I'd want to see what I've been waiting around for!), but it will probably make sense to mention on the template mode selection screen why specifically the recommendation is provided. If there are issues encountered with the theme or plugins, then the Standard mode notice should indicate that the theme had issues encountered. For Transitional mode, only theme errors would be relevant to mention as plugin issues are specifically a signal that Standard mode should not be recommended (as otherwise the sanitized functionality would not be accessible to anyone).

Something else that just came to mind in the context of reviewing the site after activation (#6071): we should make sure that the final screen again lists out the theme (if Standard/Transitional mode selected) and plugins that had validation errors, with a call to action to ensure that the related functionality still works as expected (e.g. a contact form from a forms plugin).

> **4. Settings**
> 
> Site scan can also be run from the settings screen.

I think this screen should have the same design as the Onboarding Wizard step that shows the scan results. So listing out the specific theme and plugins that have issues, with links to view the validated URLs or validation errors.

**Comment by jwold** [comment] 2021-08-31 20:32
> Icons are not distributed with plugins.

Thanks for clarifying. Didn't realize this was a limitation. I've updated the design to account for that, minus the suppression part. 

> It probably is good to keep the results on the site scan screen (as I'd want to see what I've been waiting around for!), but it will probably make sense to mention on the template mode selection screen why specifically the recommendation is provided

Agreed, for now I believe we should keep them separate. 

> If there are issues encountered with the theme or plugins, then the Standard mode notice should indicate that the theme had issues encountered.

This could probably be as simple as updating the error notices in the AMP config table to account for this. Correct? Screenshot: https://d.pr/i/tlrFka

> we should make sure that the final screen again lists out the theme (if Standard/Transitional mode selected) and plugins that had validation errors, with a call to action to ensure that the related functionality still works as expected (e.g. a contact form from a forms plugin).

I'm worried this would be a bit overwhelming, repeating that info again, especially when we'll call it out on the settings screen. 

> I think this screen should have the same design as the Onboarding Wizard step that shows the scan results. So listing out the specific theme and plugins that have issues, with links to view the validated URLs or validation errors.

This may be worth discussing live. Started to mock it up, but worried it's getting confusing. ~Link: !https://www.figma.com/file/SfMlDvHc5KHxJmAZN12PIM/?node-id=0%3A1~ (will update later)

**Comment by westonruter** [comment] 2021-09-01 20:11
> > If there are issues encountered with the theme or plugins, then the Standard mode notice should indicate that the theme had issues encountered.
> 
> This could probably be as simple as updating the error notices in the AMP config table to account for this. Correct? Screenshot: https://d.pr/i/tlrFka

Right, I guess that is captured right now, but it isn't specifically identifying the theme or plugins as being why Standard is not recommended. Basically, any results from the site scan on the previous screen could mean Standard is not recommended, at least until the loose sandboxing level is the default.

> I'm worried this would be a bit overwhelming, repeating that info again, especially when we'll call it out on the settings screen.

Yeah, it may be excessive.

> This may be worth discussing live. Started to mock it up, but worried it's getting confusing. Link: https://www.figma.com/file/SfMlDvHc5KHxJmAZN12PIM/?node-id=0%3A1

I'm not sure what is being linked to. The Figma screen is showing all the nodes and not one specifically.

**Comment by jwold** [comment] 2021-09-03 17:36
> Plugin icons are only available in the context of the directory. Icons are not distributed with plugins. So we'll have to show plugins in a list form rather than in card form.

@westonruter just curious, what other information is available? For instance, can we see `Last Updated: 2 weeks ago`, or `Version: 0.2.0`?

**Comment by jwold** [comment] 2021-09-03 20:08
@westonruter and @amedina I've updated the prototype based on our last conversation, and look forward to your feedback.

**Video:** 

https://user-images.githubusercontent.com/3411173/132060409-887cdf27-7980-4009-8147-e94f30dd0c91.mp4

This also accounts for #6071 with site review, so we'll go over them together. Happy to schedule a call Tuesday/Wednesday, otherwise we can go async. You can also checkout the prototype on [Figma](https://www.figma.com/proto/SfMlDvHc5KHxJmAZN12PIM/AMP-Design?page-id=0%3A1&node-id=3709%3A34621&viewport=388%2C48%2C0.39&scaling=min-zoom&starting-point-node-id=3707%3A31852). Thanks!

cc @delawski

**Comment by westonruter** [comment] 2021-09-07 21:06
@jwold Are the counts next to “theme issues” and “plugin issues” indicating the number of themes and plugins respectively that issues? Or is it indicating the number of issues across the themes and plugins? If the former, which seems to be indicated here, then the headings should perhaps be rather “Plugins with issues”. 

Note that there will usually be one theme, or else a parent theme and child theme. So for the theme, maybe it doesn't make sense to show it collapsed like that. Maybe for the themes it should just have the theme name and not have any count. And if there is a child theme active, have a separate row for it. The parent theme and child theme would not be in expandable drawers then.

On the settings screen, wasn't there also going to be a link off to the Validated URLs screen and/or down to the Plugin Suppression table for the user to discover what the “issues” are? I think we also need to elaborate on what “issues” means. If we're just listing out the theme/plugins which have issues, I can imagine a technical user especially exclaiming, “WHAT IS WRONG WITH MY AWESOME PLUGIN I MADE WITH MY OWN TWO HANDS?!” Or a non-technical user may throw up their hands, “I PAID $100 FOR THIS PREMIUM PLUGIN AND IT HAS ISSUES!?” Maybe we should be more explicit that issues means “AMP incompatibilities”? It's tricky because we want to also de-emphasize AMP and focus more on PX, but we don't have general PX issues yet to report. 

For technical users, perhaps there should be a link out to the Validated URLs screen so the user can review what is wrong so they aren't left wondering, both in the onboarding wizard step and on the settings/dashboard screen.

@delawski Side note, during site scanning we'll be wanting to evaluate the URLs as if Standard mode is enabled. Currently validation is performed based on whatever the currently-selected mode is, which is by default Reader mode currently. So we should come up with a way to temporarily override the mode, perhaps with a query parameter.

**Comment by amedina** [comment] 2021-09-07 23:30
+1 on providing such access to advanced users.

Could the `Browse site` button at the end be placed on the right?

**Comment by jwold** [comment] 2021-09-08 00:01
> Are the counts next to “theme issues” and “plugin issues” indicating the number of themes and plugins respectively that issues? Or is it indicating the number of issues across the themes and plugins? If the former, which seems to be indicated here, then the headings should perhaps be rather “Plugins with issues”.

Good catch. Fixed. It's supposed to be "Plugins with issues." 

> Note that there will usually be one theme, or else a parent theme and child theme. So for the theme, maybe it doesn't make sense to show it collapsed like that. Maybe for the themes it should just have the theme name and not have any count. And if there is a child theme active, have a separate row for it. The parent theme and child theme would not be in expandable drawers then.

I like that. Updated: https://d.pr/i/WQy2bG

> On the settings screen, wasn't there also going to be a link off to the Validated URLs screen and/or down to the Plugin Suppression table for the user to discover what the “issues” are? 

Good point. That got lost in the mix. Added back in: https://d.pr/i/1OmyDm

> I think we also need to elaborate on what “issues” means. If we're just listing out the theme/plugins which have issues, I can imagine a technical user especially exclaiming, “WHAT IS WRONG WITH MY AWESOME PLUGIN I MADE WITH MY OWN TWO HANDS?!” Or a non-technical user may throw up their hands, “I PAID $100 FOR THIS PREMIUM PLUGIN AND IT HAS ISSUES!?” Maybe we should be more explicit that issues means “AMP incompatibilities”? It's tricky because we want to also de-emphasize AMP and focus more on PX, but we don't have general PX issues yet to report.

What if we changed it then to "Plugins with AMP incompatibility?" That helps solve the problem in the meantime until we're ready for 2.3. Screenshot: https://d.pr/i/1OmyDm

> For technical users, perhaps there should be a link out to the Validated URLs screen so the user can review what is wrong so they aren't left wondering, both in the onboarding wizard step and on the settings/dashboard screen.

We've discussed whether to include a link or not, and this feels like evidence pointing to have a link. In this case, it's probably fine for technical or non-technical. The simplest way I can think at the moment is an anchor link out on the plugin issue list. Screenshot: https://d.pr/i/STG7ps

> Could the Browse site button at the end be placed on the right?

@amedina great question. My only concern with moving the button to the right is the imbalance it will now create with white space on the screen, especially since we're adding back in the paragraph above. Here's what it could look like: https://d.pr/i/KmtVNP

**Comment by jwold** [comment] 2021-09-08 16:55
@delawski this is now unblocked: https://www.figma.com/file/SfMlDvHc5KHxJmAZN12PIM/?node-id=0%3A1

Happy to jump on a call if clarification is needed!

cc @westonruter and @amedina

**Comment by westonruter** [comment] 2021-09-20 18:38
> We've discussed whether to include a link or not, and this feels like evidence pointing to have a link. In this case, it's probably fine for technical or non-technical. The simplest way I can think at the moment is an anchor link out on the plugin issue list. Screenshot: https://d.pr/i/STG7ps

Only thing is that there shouldn't be a link for each plugin/theme, if that link is intended to take the user to a Validated URL. A given Validated URL may have validation errors from one or more plugins, and there's no 1:1 correspondence between URLs and plugins with validation errors. So instead of there being a link with each plugin, there should be one paragraph perhaps at the top that has one single CTA to review validated URLs for any AMP compatibility issues.

Humm, that being said, we could identify a list of validated URLs that have errors for a given plugin, and the plugin-specific links could link to that subset of validated URLs. In other words, instead of linking to the Validated URLs screen at `/wp-admin/edit.php?post_type=amp_validated_url` we could link to `/wp-admin/edit.php?post_type=amp_validated_url`, let's say that a given plugin's errors were detected on the `amp_validated_url` posts with IDs 1, 2, and 3. We could link to `/wp-admin/edit.php?post_type=amp_validated_url&post__in=1,2,3` and this would just show those three Validated URLs in the post list table. (Note that `post__in` is not a public query var so this won't work out of the box.) If this is the case, then tooltip for the link with each item could be something like “Review 3 URLs on which this plugin has AMP compatibility issues.”

**Comment by westonruter** [comment] 2021-09-20 18:46
Or rather than passing in the specific post IDs, instead the URL could use the plugin slug. The only caveat here is that there is no taxonomy of the sources of validation errors, so what the Plugin Suppression table has to do is it grabs the latest 100 validated URLs, and for each that is not stale, obtains all the error sources and and builds up an in-memory index to then provide that information. In other words, we can't easily query for validated URLs that have an error which has a given source. That would be made possible with the move to custom DB tables (#5553). 

In any case, in the context of Site Scan, the most important thing is to list the validated URLs which were just scanned. Since we will have the full validation data on hand with the scan, then the plugin sources for the validation errors will be in memory already, and so the validated URLs with errors for a given plugin will be able to be obtained.

So yeah, going with what I proposed above with linking to a filter view that lists out specific validated URLs seems like the better route.

**Comment by westonruter** [comment] 2021-09-27 19:25
> Side note, during site scanning we'll be wanting to evaluate the URLs as if Standard mode is enabled. Currently validation is performed based on whatever the currently-selected mode is, which is by default Reader mode currently. So we should come up with a way to temporarily override the mode, perhaps with a query parameter.

See https://github.com/ampproject/amp-wp/pull/6615

**Comment by jwold** [comment] 2021-10-01 21:03
@delawski Alberto and I met today on the [AMP config](https://docs.google.com/document/d/1yjpVpGV6PCPs641hzmUWXzo0a46VKvjiWTytFqxtyEk/edit#heading=h.johzuescajwh) file table. We simplified a few things. 

1. Each template mode will now just have bullet points, instead of some text and a notice as the designs previously indicated. Those bullet points are listed under the right column: "Template Mode Screen Copy" in the Google doc. 
2. The recommended template mode will have `Recommended` as a badge at the top of the accordion. 
3. We'll open the `Recommended` accordion by default, and close the other two. 
4. We won't sort the template modes, but instead will have Reader on top, Transitional in the middle, and Standard on bottom. 
5. Updated the description of the page with two links below the headline. 

Figma: https://www.figma.com/file/SfMlDvHc5KHxJmAZN12PIM/AMP-Design?node-id=0%3A1

Happy to jump on a call if clarification is needed!

CC @amedina and @westonruter

**Comment by delawski** [comment] 2021-10-06 16:31
@jwold Thank you for that! I've pushed a [few commits](https://github.com/ampproject/amp-wp/pull/6610/files/4130b2a50434a83e04f86bcb7c7e31b746e30fb6..08ce98e5389e4cd8eb0daae9a999df208638a296) as part of #6610 that introduce those changes.

Here's a sample screen shot of the updated Template Modes step:

![Screenshot 2021-10-06 at 18 30 19](https://user-images.githubusercontent.com/478735/136245471-ff1e59fe-c6f7-4af3-82e8-25d02fd0d18b.png)

**Comment by jwold** [comment] 2021-10-06 17:32
You're welcome! I love it! 😀

**Closed as completed** 2021-10-28 16:11 UTC
Labels: Validation, P0, Groomed, Changelogged, Site Scanning

**Comment by milindmore22** [comment] 2021-12-08 13:28
**QA**

| Scenario                                  | Plugins          | Theme         | User Type     | Recommendation | QA Status | 
| ---------------------------- |--------------| ------------| -------------| ------------------ |------------- |
| Compatible Plugin and Theme | Yoast SEO | TwentyTwentyOne | Tech |Standard Mode recommended | ✅  |
| Compatible Plugin and Theme | Yoast SEO | TwentyTwentyOne | Non-Tech |No Recommendation | ❌   |
| Plugin has errors and Theme is compatible | Contact Form 7| TwentyTwentyOne | Tech |Transitional Mode recommended | ✅  |
| Plugin has errors and Theme is compatible | Contact Form 7| TwentyTwentyOne | Non-Tech |Transitional Mode and Reader Mode recommended | ✅  |
| Plugin is Compatible and Theme has validation errors | Yoast SEO| ColorMag | Tech |Transitional Mode and Reader Mode recommended | ✅  |
| Plugin is Compatible and Theme has validation errors | Yoast SEO| ColorMag | Non-Tech | Reader Mode recommended | ✅  |
| Plugin and Theme has validation errors | Contact Form 7| ColorMag | Tech | Reader Mode recommended | ✅  |
| Plugin and Theme has validation errors | Contact Form 7| ColorMag | Non-Tech | Reader Mode recommended | ✅  |

Here is a contradicting recommendation where **Wizard site scanner recommends Transitional mode & Reader mode and AMP settings page Site scanner recommends Standard mode when the user chooses Reader Mode Theme** 

Video for same: https://recordit.co/NEyBjW8fw1

**Comment by delawski** [comment] 2021-12-09 13:51
> Here is a contradicting recommendation where **Wizard site scanner recommends Transitional mode & Reader mode and AMP settings page Site scanner recommends Standard mode when the user chooses Reader Mode Theme**

@milindmore22 I think this works as expected but indeed may be confusing to the users.

Here's the entire flow:
- In the Wizard, a scan is done as if the site was in the Standard template mode.
- Since there's an issue with a plugin when in the Standard mode, the Reader and the Transitional modes are recommended.
- The Reader mode is selected and the user goes back to the AMP Settings screen.
- A new scan is triggered automatically since the scan results are now stale (the site is now using the Reader mode while the scan in the Wizard was done in the Standard mode). The new scan is done in the Reader mode.
- The previously offending plugin no longer causes issues in the Reader mode and so a different recommendation is offered to a user.

@westonruter What do you think about this flow? It seems to me that while technically everything works as expected, for the user this may be confusing. We may have to think of some improvements to the recommendation engine in the next release but I think we may be going down a rabbit hole here.

**Comment by westonruter** [comment] 2021-12-10 05:56
> * The previously offending plugin no longer causes issues in the Reader mode and so a different recommendation is offered to a user.

Right, I can see this particularly being an issue in the legacy Reader theme since it doesn't use standard theme hooks. Therefore if a plugin is printing something in `wp_footer`, it won't trigger an error in legacy Reader mode like it would if you're using a Reader theme. That's a tricky one. I agree it's something we should mull over and it doesn't need to be fixed right now.

**Comment by delawski** [comment] 2021-12-10 10:59
@milindmore22 Given the discussion above, do you think this issue can be moved to QA Passed lane?

**Comment by milindmore22** [comment] 2021-12-10 11:35
@delawski Not sure if this is intentional, there is one failed QA, where the user has AMP-compatible plugins and theme but didn't get any recommendation if they choose to be a non-tech user, they should be given a Standard Mode as a recommendation?

https://recordit.co/WhXdDoIKQW

**Comment by delawski** [comment] 2021-12-10 13:14
I think it is expected (as per the [template mode recommendation logic](https://github.com/ampproject/amp-wp/blob/develop/assets/src/components/use-template-mode-recommendation/index.js#L327-L354)) but I'll defer to @westonruter since he's worked on the recommendation logic most recently.

**Comment by westonruter** [comment] 2021-12-10 20:17
Yeah, that's a good observation. Basically the thinking there is that in Standard mode without loose sandboxing being enabled, it is very likely that a non-technical user could end up activating a plugin later or adding some embed code that could cause validation errors. They could then end up with a broken site without a way for visitors to access the unbroken version. So in that case, Transitional would be safer for non-technical users at the moment. We'll need to revisit this once Sandboxing graduates from experimental, as if we default to Loose then we can safely recommend Standard much more often. The ultimate goal would be to default to Standard unless the theme fails some extreme PX checks (like lacking mobile friendliness), in which case Reader would be the recommendation.
