### ISSUE TITLE
After changing slug (permalink), previous AMP page link does not redirect correctly

### ISSUE THREAD

**Issue by tranxuanthang** [Automattic/amp-wp#649] opened 2017-03-05 03:21 UTC
For example, my post's URL was:
domain/original-url-999/
Then I made some change to the permalink. Now the URL of this post is:
domain/look-the-url-changed-999/

So if I go to the previous URL (domain/original-url-999/), I will be 301 redirected to the new one (domain/look-the-url-changed-999/).
But the AMP page does not do so.

The previous AMP URL:
domain/original-url-999/amp/
And it will redirect to new ORIGINAL URL:
domain/look-the-url-changed-999/ (no /amp/ at the end of the URL).

If the post has already showed Google results and with the ⚡AMP icon, changing the permalink will make that AMP page not valid anymore. It takes time for Google to recrawl your site and update.

Meanwhile, ⚡AMP of that post is still available in the Google results. When you click in, it will show a screen inform that this site is not valid, like screenshot below:
![Image of Yaktocat](http://i.imgur.com/z39oLvY.jpg)

**Comment by mjangda** [comment] 2017-03-07 14:58
This is a duplicate of #560 and was fixed in #593

**Closed by mjangda** 2017-03-07 14:58 UTC

**Comment by kclarke10** [comment] 2018-05-17 05:55
I have this issue...still with the latest version.

URLs were https://www.domain.com/2018/oldfolder/post-name/amp/

permalink was changed as follows:
https://www.domain.com/2018/newfolder/post-name/

https://www.domain.com/2018/newfolder/post-name/amp/ is redirecting to https://www.domain.com/2018/oldfolder/post-name/

**Comment by westonruter** [comment] 2018-05-23 06:40
@kclarke10  Please share actual URLs to your site. Note that what should really matter is the `amphtml` link on the canonical URL.

**Comment by kclarke10** [comment] 2018-05-23 13:33
Can't share the url, but I see i made a mistake in my example above.

The canonical url was correct, and google results eventually aligned to the new category slug after a few days.  The traffic loss could have been avoided though if /oldfolder/post-name/amp/ redirected to /newfolder/post-name/amp/ instead of /newfolder/post-name/.
