### ISSUE TITLE
The complex CSS is removed

### ISSUE THREAD

**Issue by rafaucau** [Automattic/amp-wp#7291] opened 2022-10-10 16:07 UTC
### Bug Description

I have such CSS and it works fine on the standard version of the site:
```css 
:where(.container) {
   width: min(var(--container-max-width), 100% - calc(var(--container-padding) * 2));
   margin-inline: auto;
}
```

However, when I display the AMP version of the page, it is broken because there is only such CSS left in the `.container` class:
```css 
:where(.container) {
   margin-inline: auto;
}
```

I don't even see in the file preview that it was removed, so it's probably some kind of bug:
![image](https://user-images.githubusercontent.com/25438601/194908753-80c65382-045b-4d07-916e-eb6b6a258eed.png)
![image](https://user-images.githubusercontent.com/25438601/194908045-da94a8e2-ab0b-42bc-bf37-97375b4ea953.png)

### Expected Behaviour

It shouldn't be removed.

### PHP Version

8.1

### Plugin Version

2.3.0

### AMP plugin template mode

Transitional

### WordPress Version

6.0.2

### OS(s) Affected

All

### Browser(s) Affected

All

### Device(s) Affected

All

**Comment by thelovekesh** [comment] 2022-10-13 12:48
I believe the problem arises from `100% - calc(var(—container-padding)* 2)` which the parser is unsure how to handle, but browsers are fairly intelligent and automatically display the desired results.

It should be possible for the parser to parse it as intended if you make it a little more precise.
```diff
:where(.container) {
-  width: min(var(--container-max-width), 100% - calc(var(--container-padding) * 2));
+  width: min(var(--container-max-width), calc(100% - calc(var(--container-padding) * 2)));
   margin-inline: auto;
}
```

**Comment by rafaucau** [comment] 2022-10-13 13:24
Thanks, it helped! I'm using SCSS and had to additionally wrap it in `#{' '}` because the Sass compiler simplifies some things.
```scss
:where(.container) {
   width: #{'min(var(--container-max-width), calc(100% - calc(var(--container-padding) * 2)))'};
   margin-inline: auto;
}
```

I think this should be fixed in this plugin anyway, since the Sass compiler turns it into a shorter version by default and this is valid CSS.

**Comment by westonruter** [comment] 2022-10-13 18:08
@rafaucau This would be something needing to be fixed in the underlying [PHP-CSS-Parser](https://github.com/sabberworm/PHP-CSS-Parser) package. Could you report the issue there instead?

**Comment by rafaucau** [comment] 2022-10-13 18:35
It appears that it is already reported there: https://github.com/sabberworm/PHP-CSS-Parser/issues/388

**Comment by westonruter** [comment] 2023-03-10 19:02
Also just [raised again](https://wordpress.org/support/topic/block-theme-incompatibility/) in the support forum. I think we'll have to work up a workaround to get around this limitation of php-css-parser.

**Closed as completed** 2023-03-16 16:11 UTC
Labels: Bug, Upstream Bug, Changelogged

**Comment by westonruter** [comment] 2023-03-17 17:37
Before:

![Screenshot 2023-03-17 10 32 13](https://user-images.githubusercontent.com/134745/225977318-a79f548f-45ce-4c8d-8d11-f5654f3e63ef.png)

After:

![Screenshot 2023-03-17 10 32 43](https://user-images.githubusercontent.com/134745/225977351-bf07d02f-3595-44cf-a582-2d5e442455eb.png)

In terms of the CSS change before/after, the following complex CSS values are preserved:

```diff
669a670,672
>     --wp--preset--font-size--small: clamp(.875rem, .875rem + ((1vw - .48rem) * .24), 1rem);
>     --wp--preset--font-size--medium: clamp(1rem, 1rem + ((1vw - .48rem) * .24), 1.125rem);
>     --wp--preset--font-size--large: clamp(1.75rem, 1.75rem + ((1vw - .48rem) * .24), 1.875rem);
670a674
>     --wp--preset--font-size--xx-large: clamp(4rem, 4rem + ((1vw - .48rem) * 11.538), 10rem);
676a681
>     --wp--preset--spacing--40: clamp(1.8rem, 1.8rem + ((1vw - .48rem) * 2.885), 3rem);
678a684
>     --wp--preset--spacing--70: clamp(5rem, 5.25rem + ((1vw - .48rem) * 9.096), 8rem);
801a808
>     font-size: clamp(2.719rem, 2.719rem + ((1vw - .48rem) * 1.742), 3.625rem);
```

**Comment by westonruter** [comment] 2023-03-22 21:08
This is now released on the WordPress.org Plugin Directory.
