### ISSUE TITLE
Reader Theme: White on white content in Cover Block with predefined colors

### ISSUE THREAD

**Issue by claudiucelfilip** [Automattic/amp-wp#6039] opened 2021-04-05 14:27 UTC
## Bug Description

Using predefined (see screenshot) color as backgrounds for a Cover Block results in white on white content (see screenshot <span>#</span>2).
Trying to use an image, or a custom color behaves as expected.

## Expected Behaviour

The cover background should match the selected color in the editor.

## Steps to reproduce

1. Activate the WP AMP plugin (at least v2.0.x), with Reader mode enabled
2. Create a new post
3. Add a Cover block and select one of the predefined colors (see screenshot)
4. Make sure to Enable AMP
5. Publish
6. Check the post in AMP (ex. by appending `/amp` to the URL)

### Predefined colors
![Annotation on 2021-04-05 at 14-12-17](https://user-images.githubusercontent.com/2749938/113583780-bf7b6b80-9632-11eb-9518-68b81731dd26.png)

### White on white content
<img width="907" alt="Screenshot on 2021-04-05 at 14-13-48" src="https://user-images.githubusercontent.com/2749938/113583744-b7233080-9632-11eb-9b8f-e42a2f792bcc.png">

## Additional context

 - WordPress version: 5.7
 - Plugin version: 2.0.11
 - Gutenberg plugin version (if applicable): 10.3.1
 - AMP plugin template mode: Reader
 - PHP version: 7.4
 - OS: macOS Big Sur
 - Browser: chrome
 - Device: macbook

When using these predefined colors, a corresponding class (ex. `.has-accent-background-color`)  is added to the cover block element (`.wp-block-cover`) which is defined by the blog's theme.
Because the WP AMP plugin switches to the Legacy Reader theme, these color classes are lost. That's why, choosing a custom color works as expected.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment] 2021-04-05 16:20
Thanks for reporting the issue @claudiucelfilip. This is a duplicate of #5229. We'll try to get this fixed ASAP. In the meantime, feel free to try [this mini-plugin](https://gist.github.com/westonruter/85135e6d9e0d61865f3a63cc3ab5929e) (made specifically for fixing the issue in Twenty-Twenty) by @westonruter.

**Closed as completed by pierlon** 2021-04-05 16:20 UTC
Labels: Bug, Duplicate

**Comment by westonruter** [comment] 2021-04-05 17:17
@claudiucelfilip For your Cover Block, did you actually select an image? It seems white? Can you add a screenshot of what you see on the non-AMP version as well?

**Comment by pierlon** [comment] 2021-04-05 17:20
@westonruter To enter text on the Cover block you'd have to choose a color from the color swatch (which is not immediately noticeable).

**Comment by milindmore22** [comment] 2021-04-05 17:41
here are some test: https://plugins.dev6.rt.gw/2021/04/cover-block-test/amp/

**Comment by claudiucelfilip** [comment] 2021-04-07 11:53
@westonruter - this link show's exactly what's happening. It's happening only when you choose from the color swatch.

Thank you for looking into this!
The [mini-plugin](https://gist.github.com/westonruter/85135e6d9e0d61865f3a63cc3ab5929e) looks like a good approach, but we'll need to cover the other themes as well.

**Comment by westonruter** [comment] 2021-04-08 04:48
@claudiucelfilip Please take a look at https://github.com/ampproject/amp-wp/pull/6042 for @pierlon's work-in-progress. The lack of editor color palette standardization in themes is causing a key challenge.

**Comment by westonruter** [comment] 2021-04-22 06:47
The issue turns out to not be limited to the `editor-color-palette`. It's also an issue for `editor-font-sizes` and `editor-gradient-presets`. I believe I've accounted for all these cases now in this PR: https://github.com/ampproject/amp-wp/pull/6042.
