### ISSUE TITLE
Problem tag "rel"

### ISSUE THREAD

**Issue by overpress** [Automattic/amp-wp#357] opened 2016-04-01 08:23 UTC
Hello everyone. 

We don't know how to fix this problem that indicates Google:

<img width="776" alt="schermata 2016-04-01 alle 10 22 49" src="https://cloud.githubusercontent.com/assets/17315030/14201685/b83c121c-f7f3-11e5-8dd2-2b7e4e57697b.png">

How can we do to fix it?

Thanks

**Comment by overpress** [comment] 2016-04-17 09:30
Up

**Comment by mjangda** [comment] 2016-06-22 21:34
Dupe of #237

**Closed by mjangda** 2016-06-22 21:34 UTC
