### ISSUE TITLE
Accelerated Mobile Pages > Error in schema.org NewsArticle

### ISSUE THREAD

**Issue by moawyahr** [Automattic/amp-wp#172] opened 2016-02-03 09:06 UTC
I have this error in Webmaster tool 

Accelerated Mobile Pages > Error in schema.org NewsArticle
it says (Fix the NewsArticle structured data element in your page. AMP pages with an invalid NewsArticle structured data element may appear in Google Search results without AMP-specific display features. )

Please help ( I just deactivated AMP plugin in my website [www.runappsonpc.com](url) since it has too many problem with the new version .
other errors are : 
           

1. Accelerated Mobile Pages > Incorrectly nested tag (Ensure that all tags are nested         within the allowed parent tag. AMP pages with incorrectly nested tags may appear in Google Search results without AMP-specific display feature).

2. Accelerated Mobile Pages > Invalid attribute value (Fix invalid tag attribute values. AMP pages with invalid attribute values may appear in Google Search results without AMP-specific display features.)

3. Accelerated Mobile Pages > Prohibited attribute (Remove prohibited attributes from your page tags. AMP pages using invalid tag attributes may appear in Google Search results without AMP-specific display feature  )
 any help?

**Comment by mjangda** [comment] 2016-08-18 17:37
Closing since there aren't enough details on what the specific errors are and because the ticket is old (and we've pushed a lot of fixes since then). If you're still seeing validation errors, please open a new ticket. Thanks!

**Closed by mjangda** 2016-08-18 17:37 UTC

**Comment by designsimply** [comment] 2017-05-26 16:55
For ref, looks like a duplicate of https://github.com/Automattic/amp-wp/issues/105
