### ISSUE TITLE
AMP pages with invalid attribute values

### ISSUE THREAD

**Issue by Malagacharter** [Automattic/amp-wp#333] opened 2016-03-14 21:55 UTC
Google crawled my site finally and found the new AMP plugin.

The attribute 'rel' in tag 'a' is set to the invalid value 'motopressLightbox'

**Comment by Malagacharter** [comment] 2016-03-14 22:00
and: The attribute 'align' may not appear in tag 'p'.

**Comment by mjangda** [comment] 2016-08-18 17:47
Dupe of #237

**Closed by mjangda** 2016-08-18 17:47 UTC
