### ISSUE TITLE
Fatal error on daily cron

### ISSUE THREAD

**Issue by jonoalderson** [Automattic/amp-wp#5838] opened 2021-02-02 15:35 UTC
## Bug Description

I'm getting a daily email notifying me of a fatal error, relating to `AmpProject\AmpWP\BackgroundTask\MonitorCssTransientCaching::process()`.

I'm reasonably sure that this isn't a plugin/theme/capabilities compatability issue, as it's a pretty lightweight setup, and I'm not encountering any other issues with cron/transients/caching/plugins/etc.

## Full error

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to AmpProject\AmpWP\BackgroundTask\MonitorCssTransientCaching::process() must implement interface DateTimeInterface or be null, string given, called in /kunder/jonoal_2986/jonoal_4944/public/wp-includes/class-wp-hook.php on line 287 and defined in /kunder/jonoal_2986/jonoal_4944/public/wp-content/plugins/amp/src/BackgroundTask/MonitorCssTransientCaching.php:100
Stack trace:
#0 /kunder/jonoal_2986/jonoal_4944/public/wp-includes/class-wp-hook.php(287): AmpProject\AmpWP\BackgroundTask\MonitorCssTransientCaching->process('')
#1 /kunder/jonoal_2986/jonoal_4944/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#2 /kunder/jonoal_2986/jonoal_4944/public/wp-includes/plugin.php(551): WP_Hook->do_action(Array)
#3 phar:///usr/bin/wp-cli/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(343): do_action_ref_array('amp_monitor_css...', Array)
#4 phar:///usr/bin/wp-cli/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(265): Cron_Event_Command::run_event in /kunder/jonoal_2986/jonoal_4944/public/wp-content/plugins/amp/src/BackgroundTask/MonitorCssTransientCaching.php on line 100
Fatal error: Uncaught TypeError: Argument 1 passed to AmpProject\AmpWP\BackgroundTask\MonitorCssTransientCaching::process() must implement interface DateTimeInterface or be null, string given, called in /kunder/jonoal_2986/jonoal_4944/public/wp-includes/class-wp-hook.php on line 287 and defined in /kunder/jonoal_2986/jonoal_4944/public/wp-content/plugins/amp/src/BackgroundTask/MonitorCssTransientCaching.php:100
Stack trace:
#0 /kunder/jonoal_2986/jonoal_4944/public/wp-includes/class-wp-hook.php(287): AmpProject\AmpWP\BackgroundTask\MonitorCssTransientCaching->process('')
#1 /kunder/jonoal_2986/jonoal_4944/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#2 /kunder/jonoal_2986/jonoal_4944/public/wp-includes/plugin.php(551): WP_Hook->do_action(Array)
#3 phar:///usr/bin/wp-cli/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(343): do_action_ref_array('amp_monitor_css...', Array)
#4 phar:///usr/bin/wp-cli/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(265): Cron_Event_Command::run_event in /kunder/jonoal_2986/jonoal_4944/public/wp-content/plugins/amp/src/BackgroundTask/MonitorCssTransientCaching.php on line 100
 [31;1mError: [0m There has been a critical error on this website.Learn more about debugging in WordPress. There has been a critical error on this website.
```

## Additional context

 - WordPress version: 5.6
 - Plugin version: 2.0.10
 - AMP plugin template mode: Standard
 - PHP version: Linux
 - OS: 7.3.25

### Site Health dump
```
### wp-core ###

version: 5.6
site_language: en_GB
user_language: en_GB
timezone: +00:00
permalink: /%category%/%postname%/
https_status: true
multisite: false
user_registration: 0
blog_public: 1
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /kunder/jonoal_2986/jonoal_4944/public
wordpress_size: 55.45 MB (58145522 bytes)
uploads_path: /kunder/jonoal_2986/jonoal_4944/public/wp-content/uploads
uploads_size: 231.99 MB (243259764 bytes)
themes_path: /kunder/jonoal_2986/jonoal_4944/public/wp-content/themes
themes_size: 318.05 KB (325679 bytes)
plugins_path: /kunder/jonoal_2986/jonoal_4944/public/wp-content/plugins
plugins_size: 64.34 MB (67463417 bytes)
database_size: 13.58 MB (14237696 bytes)
total_size: 365.67 MB (383432078 bytes)

### wp-dropins (3) ###

advanced-cache.php: true
db.php: true
object-cache.php: true

### wp-active-theme ###

name: JonoAlderson.com (jonoaldersondotcom)
version: undefined
author: Anonymous
author_website: (undefined)
parent_theme: none
theme_features: core-block-patterns, menus, post-thumbnails
theme_path: /kunder/jonoal_2986/jonoal_4944/public/wp-content/themes/jonoaldersondotcom
auto_update: Disabled

### wp-plugins-active (14) ###

Advanced Custom Fields: version: 5.9.4, author: Elliot Condon, Auto-updates disabled
Akismet Anti-Spam: version: 4.1.8, author: Automattic, Auto-updates disabled
AMP: version: 2.0.10, author: AMP Project Contributors, Auto-updates disabled
Cloudflare: version: 3.8.9, author: Cloudflare, Inc., Auto-updates disabled
Compress JPEG & PNG images: version: 3.2.1, author: TinyPNG, Auto-updates disabled
PWA: version: 0.6.0, author: PWA Plugin Contributors, Auto-updates disabled
Regenerate Thumbnails: version: 3.1.4, author: Alex Mills (Viper007Bond), Auto-updates disabled
Servebolt Optimizer: version: 2.1.5, author: Servebolt, Auto-updates disabled
Very Simple Event List: version: 12.3, author: Guido, Auto-updates disabled
W3 Total Cache: version: 2.1.0, author: BoldGrid, Auto-updates disabled
WP-Optimize - Clean, Compress, Cache: version: 3.1.6, author: David Anderson, Ruhani Rabin, Team Updraft, Auto-updates disabled
WP Mail SMTP: version: 2.5.1, author: WPForms, Auto-updates disabled
Yoast SEO Links plugin: version: 15.7-RC5, author: Joost de Valk, Auto-updates disabled
Yoast SEO Premium: version: 15.6.2, author: Team Yoast, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1690
imagemagick_version: ImageMagick 6.9.10-68 Q16 x86_64 2020-04-01 https://imagemagick.org
file_uploads: File uploads is turned off
post_max_size: 50M
upload_max_filesize: 50M
max_effective_size: 50 MB
max_file_uploads: 20
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 186 GB
	imagick::RESOURCETYPE_DISK: 9.2233720368548E+18
	imagick::RESOURCETYPE_FILE: 768
	imagick::RESOURCETYPE_MAP: 186 GB
	imagick::RESOURCETYPE_MEMORY: 93 GB
	imagick::RESOURCETYPE_THREAD: 20
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Linux 5.4.41-0.x86_64 x86_64
httpd_software: Apache/2.4
php_version: 7.3.25 64bit
php_sapi: apache2handler
max_input_variables: 1000
time_limit: 600
memory_limit: 96M
max_input_time: 90
upload_max_filesize: 50M
php_post_max_size: 50M
curl_version: 7.29.0 NSS/3.53.1
suhosin: false
imagick_availability: true
pretty_permalinks: true
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 10.4.17-MariaDB-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $

### wp-constants ###

WP_HOME: https://www.jonoalderson.com
WP_SITEURL: https://www.jonoalderson.com
WP_CONTENT_DIR: /kunder/jonoal_2986/jonoal_4944/public/wp-content
WP_PLUGIN_DIR: /kunder/jonoal_2986/jonoal_4944/public/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 96M
WP_DEBUG: undefined
WP_DEBUG_DISPLAY: undefined
WP_DEBUG_LOG: undefined
SCRIPT_DEBUG: false
WP_CACHE: true
CONCATENATE_SCRIPTS: false
COMPRESS_SCRIPTS: true
COMPRESS_CSS: true
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### wp_mail_smtp ###

version: 2.5.1
license_key_type: lite
debug: No debug notices found.
db_tables: wp_wpmailsmtp_tasks_meta
lite_install_date: Jan 24, 2021 @ 9:48pm

### amp_wp ###

amp_mode_enabled: standard
amp_reader_theme: legacy
amp_templates_enabled: post, page, is_singular, is_front_page, is_home, is_archive, is_author, is_date, is_search, is_404, is_category, is_tag, is_tax[event_cat], is_post_type_archive[event]
amp_serve_all_templates: true
amp_css_transient_caching_disabled: n/a
amp_css_transient_caching_threshold: 5000 transients per day
amp_css_transient_caching_sampling_range: 14 days
amp_css_transient_caching_transient_count: 140
amp_css_transient_caching_time_series: 
	20210125: 80
	20210126: 104
	20210128: 110
	20210129: 118
	20210130: 132
	20210131: 138
	20210201: 139
amp_libxml_version: 2.9.1
```

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment] 2021-02-02 16:56
This may have been already fixed in #5515 as the arguments for the `AmpProject\AmpWP\BackgroundTask\MonitorCssTransientCaching::process()` method have changed:

https://github.com/ampproject/amp-wp/blob/a42e72122d1fa948876a7ef79e2626f4ac276541/src/BackgroundTask/MonitorCssTransientCaching.php#L104

**Comment by westonruter** [comment] 2021-02-02 17:34
Oh, I didn't realize this was an issue in 2.0.10. I thought it was in 2.1-alpha. 

I think we should fix this for 2.0.11 specifically.

**Comment by westonruter** [comment] 2021-02-02 23:22
I see the problem. The issue is that the `process` method is specifying the `$date` parameter as being a `DateTimeInterface`:

https://github.com/ampproject/amp-wp/blob/501d13f3f63915b51f106ea0fb7ea60d67b0f557/src/BackgroundTask/MonitorCssTransientCaching.php#L95-L111

However, when `MonitorCssTransientCaching` is registered, the `process` method is added as an action:

https://github.com/ampproject/amp-wp/blob/501d13f3f63915b51f106ea0fb7ea60d67b0f557/src/BackgroundTask/CronBasedBackgroundTask.php#L54

When WordPress does an action and no arguments are supplied, it [passes an empty string](https://github.com/WordPress/wordpress-develop/blob/3c3590103a40f046cc9edaaaac6467a852c5929d/src/wp-includes/plugin.php#L477-L478). And since an empty `string` is not of type `DateTimeInterface`, then a fatal error ensues. I've opened a fix in #5841.

This is only an issue in the `2.0` branch, as in `develop` the `process` method now takes arbitrary args:

https://github.com/ampproject/amp-wp/blob/4395c80314c30989dcd016cee09491a77c217812/src/BackgroundTask/MonitorCssTransientCaching.php#L95-L112

**Comment by westonruter** [comment] 2021-02-02 23:28
I'm also able to reproduce the issue using WP-CLI:

```
$ wp cron event run --all
Executed the cron event 'amp_validated_url_stylesheet_gc' in 0.007s.
Executed the cron event 'amp_validated_url_stylesheet_gc' in 0.009s.
Executed the cron event 'wp_privacy_delete_old_export_files' in 0.006s.
Executed the cron event 'amp_validate_urls' in 0.005s.
Executed the cron event 'wp_site_health_scheduled_check' in 3.853s.
Executed the cron event 'recovery_mode_clean_expired_keys' in 0.007s.
Executed the cron event 'wp_version_check' in 1.817s.
Executed the cron event 'wp_update_plugins' in 0.451s.
Executed the cron event 'wp_update_themes' in 0.008s.
Executed the cron event 'wp_scheduled_delete' in 0.006s.
Executed the cron event 'delete_expired_transients' in 0.008s.
Executed the cron event 'wp_scheduled_auto_draft_delete' in 0.006s.
Executed the cron event 'amp_monitor_css_transient_caching' in 0.007s.
Fatal error: Uncaught TypeError: Argument 1 passed to AmpProject\AmpWP\BackgroundTask\MonitorCssTransientCaching::process() must implement interface DateTimeInterface or be null, string given, called in /app/public/wp-includes/class-wp-hook.php on line 287 and defined in /app/public/wp-content/plugins/amp/src/BackgroundTask/MonitorCssTransientCaching.php:100
Stack trace:
#0 /app/public/wp-includes/class-wp-hook.php(287): AmpProject\AmpWP\BackgroundTask\MonitorCssTransientCaching->process('')
#1 /app/public/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array)
#2 /app/public/wp-includes/plugin.php(551): WP_Hook->do_action(Array)
#3 phar:///usr/local/bin/wp/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(293): do_action_ref_array('amp_monitor_css...', Array)
#4 phar:///usr/local/bin/wp/vendor/wp-cli/cron-command/src/Cron_Event_Command.php(262): Cron_Event_Command::run_event(Object(stdClass))
#5 [internal function]: Cron_Event_Command->run(Array, Array)
#6 phar:///usr/local/bin/wp/vendor/wp-cli/wp-cli/p in /app/public/wp-content/plugins/amp/src/BackgroundTask/MonitorCssTransientCaching.php on line 100
Error: There has been a critical error on this website.Learn more about debugging in WordPress. There has been a critical error on this website.
```

**Comment by westonruter** [comment] 2021-02-03 01:05
I don't think my assessment in https://github.com/ampproject/amp-wp/issues/5838#issuecomment-772083669 is completely accurate given the current state of the code, because `wp_schedule_event()` is being called without `$args` which means an empty array will be passed:

https://github.com/ampproject/amp-wp/blob/501d13f3f63915b51f106ea0fb7ea60d67b0f557/src/BackgroundTask/CronBasedBackgroundTask.php#L89

I saw there were actually two separate `amp_monitor_css_transient_caching` events scheduled, one presumably had empty args and another had an args of `[ '' ]`, and the latter one is the one that was causing a fatal error. 

So where did the the one get scheduled with an empty string as args? I think the answer is in the `develop` branch in the `RecurringBackgroundTask`:

https://github.com/ampproject/amp-wp/blob/4395c80314c30989dcd016cee09491a77c217812/src/BackgroundTask/RecurringBackgroundTask.php#L25-L46

So here the `schedule_event()` method runs at `admin_init` and when `do_action()` runs it will pass an empty string as `$args[0]` to `schedule_event()`, which then gets passed to `$args`.

I think what happened is that the plugin was updated to 2.1-alpha and then it was downgraded to 2.0.10, resulting in two separate scheduled events, one with empty args (2.0.x) and another with args having an empty strings as its one arg (2.1-alpha).

I just tried purging cron events via `wp cron event delete amp_monitor_css_transient_caching` and then (after accessing the admin to cause events to get scheduled) when running `wp option get cron` I saw:

```php
  1612400193 =>
  array (
    'amp_monitor_css_transient_caching' =>
    array (
      '40cd750bba9870f18aada2478b24840a' =>
      array (
        'schedule' => 'daily',
        'args' =>
        array (
        ),
        'interval' => 86400,
      ),
    ),
  ),
```

Note that `args` is an _empty_ array.

If I then try installing 2.1-alpha, re-access the admin to cause event scheduling, then `wp option get cron` shows two entries:

```php
  1612400858 =>
  array (
    'amp_monitor_css_transient_caching' =>
    array (
      '40cd750bba9870f18aada2478b24840a' =>
      array (
        'schedule' => 'daily',
        'args' =>
        array (
        ),
        'interval' => 86400,
      ),
    ),
  ),
  1612400896 =>
  array (
    'amp_monitor_css_transient_caching' =>
    array (
      '5b448a7bdbeea0be7d7f758f5f8ee90b' =>
      array (
        'schedule' => 'daily',
        'args' =>
        array (
          0 => '',
        ),
        'interval' => 86400,
      ),
    ),
  ),
```

So now there are two events, one with no args and another with one empty string arg.

@jono-alderson did you upgrade to 2.1-alpha and then downgrade to stable?

**Comment by westonruter** [comment] 2021-02-03 01:10
If so, I see there being two actions needed here:

1. Make 2.0 branch more resilient to an empty string being supplied as a scheduled event arg. See #5841.
2. Update `develop` branch to not pass an empty string as an argument so that this doesn't happen in the first place. See #5842.

**Closed as completed** 2021-02-03 03:42 UTC
Labels: Bug, P0, Groomed, Changelogged

**Comment by jonoalderson** [comment] 2021-02-03 08:30
Ah, yes, it was definitely the upgrade path issue!
Great catch; sorry for having sent you on such a deep dive for an edge case!
