### ISSUE TITLE
CSS sanitizer removes CSS variables

### ISSUE THREAD

**Issue by sboerrigter** [Automattic/amp-wp#5023] opened 2020-07-10 14:56 UTC
## Bug Description

CSS variables (such as `border-color:rgba(0,0,0,var(--border-opacity))`) are not included in the CSS output on AMP pages. 

## Expected Behaviour

If the HTML marktup contains a CSS class with a CSS variable (such as `--border-opacity: 0;`) the styling for that css variable should be included in the CSS output.

## Steps to reproduce

1. Edit a template file (such as `single.php`).
2. add a CSS class with a CSS variable (such as `<h1 class="border-opacity-0">Blah...</h1>`).
3. add styling for that CSS class and the CSS variable (such as `--border-opacity: 0;` and `.border-opacity-0 { border-color: rgba(0,0,0,var(--border-opacity))}`) or load [Tailwind CSS ](https://tailwindcss.com/docs/installation/#using-tailwind-via-cdn).
5. Visit the regular version of the page and see that the styling is applied.
6. Visit the AMP version of the page and see that the styling is not applied.

## Additional context

 - WordPress version: 5.4.2
 - Plugin version: 1.5.4
 - AMP plugin template mode: Transitional

CSS variables are commonly used in the popular [Tailwind CSS framework](https://tailwindcss.com/docs/width).

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by pierlon** [comment] 2020-07-10 15:47
This should not be the case. Our included CSS tree shaker only removes unused CSS from AMP pages; if the CSS is not targeting an HTML element on the page, it will be removed.

For example (with AMP Plugin v1.5.5), if I add an HTML block with the following content:

```html
<h1 class="success">Blah...</h1>

<style>
body {
  --green: #1f1f;
}

.success {
  color: var(--green);
}
</style>
```

I can see that the HTML element is styled appropriately:

![image](https://user-images.githubusercontent.com/16200219/87172917-84772200-c2c4-11ea-8ec0-2a254bf38d2a.png)

**Comment by westonruter** [comment] 2020-07-10 17:44
The issue is `var(--varname)` being nested inside of other CSS functions. 

Consider this example:

```html
<p class="opacity opacity1">Opacity1!</p>
<p class="opacity opacity2">Opacity2!</p>
<p class="opacity opacity3">Opacity3!</p>

<style>
body {
  --opacity: 0.2;
}
.opacity {
  background: cyan;
}
.opacity1 {
  opacity: var(--opacity);
  color: rgb(0,0,255);
}
.opacity2 {
  color: rgba(0,0,255,0.2);
}
.opacity3 {
  color: rgba(0,0,255,var(--opacity));
}
</style>
```

The correct rendering is:

> ![image](https://user-images.githubusercontent.com/134745/87182714-85df2500-c299-11ea-8b48-8bb5c6ffa9d7.png)

Note Opacity2 and Opacity3 look the same.

But on an AMP page it is rendered incorrectly, where the `color` value fails to be parsed:

> ![image](https://user-images.githubusercontent.com/134745/87182745-98595e80-c299-11ea-95d1-f7400005946f.png)

This is due to the `var()` being nested inside of the `rgba()` function. 

This is a known issue in the PHP-CSS-Parser: 

https://github.com/sabberworm/PHP-CSS-Parser/issues/196
https://github.com/sabberworm/PHP-CSS-Parser/issues/186

There is a new PR upstream to fix the issue: https://github.com/sabberworm/PHP-CSS-Parser/pull/197

**Comment by sboerrigter** [comment] 2020-07-10 18:10
Cool, thanks for the quick help guys. 

Do you think this fix will make it into version 1.6 of the AMP plugin? And when is that version planned to release? In the [milestone](https://github.com/ampproject/amp-wp/milestone/28) I see "Due by August 01, 2020". Is that correct?

**Comment by westonruter** [comment] 2020-07-10 19:44
We've adjusted the milestone date back to August 15th. If the issue is fixed upstream in PHP-CSS-Parser then we should definitely include the fix in v1.6.

**Comment by westonruter** [comment] 2020-07-21 18:53
Upstream PR has been merged: https://github.com/sabberworm/PHP-CSS-Parser/pull/197

**Closed as completed** 2020-07-22 06:18 UTC
Labels: Bug, CSS, Upstream Bug, WS:Core, Groomed, Changelogged

**Comment by westonruter** [comment] 2020-07-22 06:19
@sboerrigter Please test the build with the patches applied to verify the issue is fixed: https://github.com/ampproject/amp-wp/pull/5081#issuecomment-662210637

**Comment by sboerrigter** [comment] 2020-07-22 09:07
@westonruter yep, the patch fixed the issue. Thanks!

**Comment by sboerrigter** [comment] 2022-01-14 16:35
I updated the CSS framework we use (Tailwind CSS 2 > 3) and ran into this same error. After some debugging and googling I found this issue again that I created myself 😐. In Tailwind 3 the CSS with CSS variables looks like this:

```
.bg-brand-500{
  --tw-bg-opacity: 1;
  background-color: rgb(20 184 166 / var(--tw-bg-opacity));
}
```

I've fixed this now by replacing all CSS variables using https://github.com/MadLittleMods/postcss-css-variables, but this should probably be fixed in the AMP plugin or in https://github.com/sabberworm/PHP-CSS-Parser/.

**Comment by westonruter** [comment] 2022-01-14 17:06
@sboerrigter So the issue didn't happen in Tailwind CSS 2 but started happening again with v3? Or was there a change to PHP-CSS-Parser in a different version of the AMP plugin that caused the regression?

**Comment by sboerrigter** [comment] 2022-01-14 17:13
@westonruter yes, I've tested this with previous versions of the AMP plugin as well.

**Comment by westonruter** [comment] 2022-01-14 18:15
So to confirm, there's some difference in Tailwind CSS v3 that is causing this regression.

There are a couple open issues regarding CSS variables. I think the one in question is https://github.com/sabberworm/PHP-CSS-Parser/issues/186.

**Comment by sboerrigter** [comment] 2022-01-15 08:54
That's right. The CSS output from Tailwind 3 is different then the CSS output from Tailwind 2 (see my previous comments). 

I don't have this problem if I downgrade Tailwind to V2 and leave everything else in my codebase the same.

**Comment by emidiao** [comment] 2022-03-14 14:52
@sboerrigter I am having the same problem with tailwind3, if possible would you please share how you solved using https://github.com/MadLittleMods/postcss-css-variables ?

**Comment by sboerrigter** [comment] 2022-03-14 19:00
@emidiao i've installed that package and added something like this to my `postcss.config.js` file:

```
module.exports = {
  plugins: [
    require("tailwindcss"),
    ...(process.env.IS_AMP === "true"
      ? [require("postcss-css-variables")]
      : [])
  ],
};
```

And I added a NPM script to to my `package.json` file to build the CSS output for AMP without CSS variables:

```
"scripts": {
  "build": "postcss styles/main.css -o dist/main.css",
  "build:amp": "IS_AMP=true postcss styles/amp.css -o dist/amp.css"
}
```

Good luck!
