### ISSUE TITLE
SiteOrigin Page Builder says WP Widget Text is missing (works fine when AMP is disabled)

### ISSUE THREAD

**Issue by KZeni** [Automattic/amp-wp#4618] opened 2020-04-21 20:18 UTC
## Bug Description

It seems like this issue came up with another AMP plugin (https://wordpress.org/plugins/accelerated-mobile-pages/) over a year ago per https://wordpress.org/support/topic/latest-version-makes-wp-widget-text-go-missing/ & was possibly resolved for that plugin (at least the topic has since been closed).

However, it appears this is an issue now for this AMP plugin.

I'm using SiteOrigin Page Builder on a site and it's giving me an error of WP Widget Text (the standard "Text" widget for WordPress) is missing when it was previously working (screenshot: https://cloudup.com/cOfuZrOQszc). Disabling this plugin has the problem go away while re-enabling has the issue come back so something probably happened in a recent update to have this issue come up (which another AMP plugin also came across).

I'd love to see this problem resolved so I can re-enable this plugin.

## Expected Behaviour

The text widget is working & readily available while using SiteOrigin Page Builder and AMP at the same time.

## Steps to reproduce

1. Install & enable SiteOrigin Page Builder and AMP
2. Try to use the text widget
3. Toggle the AMP plugin off & on to see how the text widget stops working (goes "missing") when AMP is enabled.

## Screenshots

https://cloudup.com/cOfuZrOQszc

**Comment by KZeni** [comment] 2020-04-21 20:20
This is also mentioned on WP.org support forum at https://wordpress.org/support/topic/page-builder-says-wp-widget-text-is-missing-works-fine-when-amp-is-disabled/ for better visibility for those experiencing the issue who aren't privy to GitHub & more technical details since widgets not working does seem like an important issue to fix.

**Comment by westonruter** [comment] 2020-04-21 20:37
I believe this is a duplicate of #4492. I'm trying to figure out the best solution for this.

**Comment by KZeni** [comment] 2020-04-21 20:40
Ah, I looked around & thought that might've been a different issue at first glance since it's for a separate widget, but it really does seem like it could be related.

Thanks for the update!

**Comment by westonruter** [comment] 2020-04-21 20:59
Please subscribe to the other issue for updates.

**Closed as completed by westonruter** 2020-04-21 20:59 UTC
Labels: Duplicate

**Comment by westonruter** [comment] 2020-04-22 00:41
@KZeni There is now a pre-release build with a fix available for testing: https://github.com/ampproject/amp-wp/pull/4515#issuecomment-617481804

**Comment by KZeni** [comment] 2020-04-22 03:07
Thank you and all involved with this fix. I can happily report that the issue has been resolved in my use case.
