### ISSUE TITLE
Activating Gutenberg messed backend styling

### ISSUE THREAD

**Issue by milindmore22** [Automattic/amp-wp#6235] opened 2021-05-14 10:25 UTC
## Bug Description

Activating Gutenberg messed AMP settings page styling a little bit

## Expected Behaviour

Activating any plugin should not have effects on settings

## Steps to reproduce

1. Install and Activate AMP and Gutenberg plugin
2. Visit the AMP settings page
4. See Template Mode toggle.

## Screenshots

![image](https://user-images.githubusercontent.com/1132541/118257535-5e19a880-b4cc-11eb-87b7-c1092004b156.png)

## Additional context

 - WordPress version: 5.7.2
 - Plugin version: 2.1.1
 - Gutenberg plugin version (if applicable): 10.6.0
 - AMP plugin template mode: Transtional Mode
 - PHP version: 7.4
 - OS: Mac Os
 - Browser: Chrome
 - Device: Macbook Air

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment] 2021-05-14 17:30
Thanks. I saw this too but I wasn't sure if it was a problem with my Gutenberg build or it was a new issue.

**Comment by pierlon** [comment] 2021-05-14 17:31
Might be because we're bundling the CSS from `@wordpress/components` for the settings page. Investigating...

**Comment by westonruter** [comment] 2021-05-17 19:01
There is a difference in styling is due to a missing CSS rule in Gutenberg (`gutenberg/build/components/style.css`) which is present in core (`wp-includes/css/dist/components/style.css`):

![image](https://user-images.githubusercontent.com/134745/118541770-f1d6b900-b706-11eb-92dd-485aaf814964.png)

**Comment by pierlon** [comment] 2021-05-17 19:03
Currently working on migrating used styles from `wp-components` into the plugin so we don't need to rely on it. If that's the only style rule missing we could add it and go ahead with that in the interim.

**Comment by westonruter** [comment] 2021-05-17 19:06
Present in Gutenberg 10.5.4: https://github.com/WordPress/gutenberg/blob/v10.5.4/packages/components/src/visually-hidden/style.scss
And present in 10.6.1: https://github.com/WordPress/gutenberg/blob/v10.6.1/packages/components/src/visually-hidden/style.scss
But this file is missing in v10.6.0. Nevertheless, the styles are still broken in v10.6.1.

It looks like this problem was introduced in https://github.com/WordPress/gutenberg/pull/31244.

**Comment by pierlon** [comment] 2021-05-18 02:07
> It looks like this problem was introduced in WordPress/gutenberg#31244.

That PR has just been reverted via https://github.com/WordPress/gutenberg/pull/31882. I'll continue the work on migrating the styles into the appropriate Gutenberg components but I think this issue can be punted to the next release for now.

**Comment by pierlon** [comment] 2021-05-18 02:09
I can confirm that the Settings screen is back to normal for now (when on 67f2cf8f43217b339df04b2823531cda0a189001 and https://github.com/WordPress/gutenberg/commit/b5f6955742e784f11828e1dacba4361713135963):

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/16200219/118579667-04d8a000-b77e-11eb-8d13-e750d10a77df.png">

**Comment by westonruter** [comment] 2021-05-18 03:13
Confirmed. Fixed in Gutenberg v10.6.1.

**Comment by westonruter** [comment] 2021-07-29 20:57
@pierlon this is being fixed in what you're doing to fix #6490?

**Comment by pierlon** [comment] 2021-07-29 21:02
Oh yes that would resolve this issue as well. I'll create a separate PR with those changes then as they've become mutually exclusive to the actual issue I was fixing.

**Comment by westonruter** [comment] 2021-08-26 16:27
This issue has arisen again when Gutenberg 11.3.0 is active:

![image](https://user-images.githubusercontent.com/134745/131000241-42044411-3230-439a-abe0-533177ce2ece.png)

**Comment by westonruter** [comment] 2021-08-26 17:23
@pierlon Is there a quick fix that would address this for 2.1.4?

**Comment by pierlon** [comment] 2021-08-26 17:32
Just created #6570 as a fix.

**Comment by westonruter** [comment] 2021-08-27 16:42
My cherry-pick (d4d2a7b) onto the 2.1 branch failed: https://github.com/ampproject/amp-wp/runs/3444490820#step:7:109

It appears due to the Gutenberg packages not being updated.

@pierlon Is this something that can be easily backported to 2.1.x? Or is it too much of a headache?

**Comment by pierlon** [comment] 2021-08-27 17:05
It seems all that's needed is to update the JS test snapshots to match the version of the `VisuallyHidden` component in that branch.

**Comment by westonruter** [comment] 2021-08-27 17:18
Great! Fixed as of https://github.com/ampproject/amp-wp/pull/6575.

**Comment by westonruter** [comment] 2021-08-30 21:43
Humm. With the latest Gutenberg active, I'm seeing the same issue still on 2.1.4-alpha:

![image](https://user-images.githubusercontent.com/134745/131409657-a35c068d-a686-4ac8-9d7f-5926cbfe5d82.png)

**Comment by pierlon** [comment] 2021-08-30 21:54
Can confirm, looking into this.

**Comment by westonruter** [comment] 2021-08-30 21:55
The issue is not present on 2.2-alpha:

![image](https://user-images.githubusercontent.com/134745/131410525-a1fb0f56-09c4-404b-967e-b18887d962ef.png)

2.1.4-alpha | 2.2-alpha
-----------|------------
<img width="1399" alt="Screen Shot 2021-08-30 at 14 47 55" src="https://user-images.githubusercontent.com/134745/131410724-365de645-9a56-4c60-ad99-2002f23aa7b0.png"> | <img width="1395" alt="Screen Shot 2021-08-30 at 14 52 43" src="https://user-images.githubusercontent.com/134745/131410729-f60cc438-879f-46b4-9ed5-b4b219d36447.png">

**Comment by westonruter** [comment] 2021-08-30 22:25
I just noticed this issue is also present in the Reader theme carousel pagination:

![image](https://user-images.githubusercontent.com/134745/131413723-fa9286b3-e2d8-4294-9934-118627c16148.png)

**Comment by pierlon** [comment] 2021-08-30 22:40
The version of the `@wordpress/components` package on the 2.1 branch does not include the styles for the `VisuallyHidden` component, so I'm working on updating the package to the latest stable version. That will also mean updating all the other Gutenberg packages to ensure compatibility between the packages.

**Comment by westonruter** [comment] 2021-08-31 04:05
Fixed for 2.1.4 via https://github.com/ampproject/amp-wp/pull/6585. Ready for QA.

**Closed as completed by westonruter** 2021-08-31 04:05 UTC
Labels: Bug

**Comment by westonruter** [comment] 2021-08-31 05:02
## ✅ WordPress 5.6.4 w/ Gutenberg

Settings Screen | Onboarding Wizard | Post Editor
----------------|---------------------|-------------
![image](https://user-images.githubusercontent.com/134745/131443886-bac5eb7f-45f1-4046-ba2d-c06a0d149ac7.png) | ![image](https://user-images.githubusercontent.com/134745/131443964-0b53d290-c2a8-4e51-baf7-f392cef9c697.png) | ![image](https://user-images.githubusercontent.com/134745/131444034-a2ffe6c5-16a9-47cb-b97e-787d5f4c6214.png)

## ✅ WordPress 5.7.2 w/ Gutenberg

Settings Screen | Onboarding Wizard | Post Editor
----------------|---------------------|-------------
![image](https://user-images.githubusercontent.com/134745/131444319-d1d6baa6-6e03-487c-aad7-6329f37effe7.png) | ![image](https://user-images.githubusercontent.com/134745/131444371-aa7bfe20-f2d9-4869-8c87-46f9cc1b5bd9.png) | ![image](https://user-images.githubusercontent.com/134745/131444421-d6618307-1fdf-4650-a442-2046f5dd395a.png)

## ✅ WordPress 5.8 w/ Gutenberg 

Settings Screen | Onboarding Wizard | Post Editor
----------------|---------------------|-------------
![image](https://user-images.githubusercontent.com/134745/131444724-c2ac9ad0-ef2a-4980-a5c3-4f5a74c3e22e.png) | ![image](https://user-images.githubusercontent.com/134745/131444739-d170d05b-5ab1-436e-886a-ad6dfc377d4a.png) | ![image](https://user-images.githubusercontent.com/134745/131444773-c98b7888-6bed-4a23-ad95-ec89c99924c2.png)

**Comment by westonruter** [comment] 2021-08-31 05:11
## ✅ WordPress 5.6.4 w/o Gutenberg

Settings Screen | Onboarding Wizard | Post Editor
----------------|---------------------|-------------
![image](https://user-images.githubusercontent.com/134745/131445109-1fcea0ba-4061-4640-bc52-762f7bc4d782.png) | ![image](https://user-images.githubusercontent.com/134745/131445158-94383dc3-507a-46a4-9991-c65797721a4e.png) | ![image](https://user-images.githubusercontent.com/134745/131445211-ed8f5e6b-71ce-41f3-a525-6108ee183b8c.png)

## ✅ WordPress 5.8 w/o Gutenberg

Settings Screen | Onboarding Wizard | Post Editor
----------------|---------------------|-------------
![image](https://user-images.githubusercontent.com/134745/131445571-33d21181-4e2e-4aca-a4f3-f0fce14f849e.png) | ![image](https://user-images.githubusercontent.com/134745/131445607-0a7098f8-8341-4d5f-aad6-898bf841cdd6.png) | ![image](https://user-images.githubusercontent.com/134745/131445630-61826c4b-0a78-4ab4-bb84-9f54c16ca757.png)

**Comment by westonruter** [comment] 2021-08-31 05:20
I've tested various screens in the different versions and everything seems to check out. 

@delawski Maybe you have some other areas in mind to test as well. Otherwise, I'm moving this to **QA Passed**.

**Comment by delawski** [comment] 2021-08-31 16:07
> @delawski Maybe you have some other areas in mind to test as well. Otherwise, I'm moving this to QA Passed.

All good here 👍
