### ISSUE TITLE
AMP box doens't appear

### ISSUE THREAD

**Issue by br0k3n** [Automattic/amp-wp#646] opened 2017-03-01 09:28 UTC
Hi, I install your plugin, but the proper box doesn't appear on any blog post.

How can I solve?
Thanks

**Comment by amedina** [comment] 2017-06-02 01:15
Sorry, it is not clear what the problem is; could you provide examples or links to reproduce the error?

**Comment by amedina** [comment] 2017-06-02 01:15
Closing for now. Feel free to re-open if you haven't been able to get your site going with the plugin and can provide more data to reproduce.

**Closed by amedina** 2017-06-02 01:15 UTC
