### ISSUE TITLE
Figcaption misalignment using default editor on Safari mobile.

### ISSUE THREAD

**Issue by jamesozzie** [Automattic/amp-wp#6035] opened 2021-04-02 13:30 UTC
## Bug Description

As [reported in the WordPress support forums](https://wordpress.org/support/topic/amp-plugin-disrupts-image-caption-alignment/#post-14268579) when adding an image caption on images that have centered or no alignment the captions in AMP URLs are misplaced - on mobile devices and only on first load. 

An example URL where this can behavior can be seen is [here](https://undiscoveredberchtesgaden.com/self-guided-tour-of-lake-konigssee/), with screenshots below:

![image](https://user-images.githubusercontent.com/41326532/113419294-0fea9300-93bf-11eb-8142-3670f82f3cf8.png)

![image](https://user-images.githubusercontent.com/41326532/113418428-60f98780-93bd-11eb-93c5-2abbdc66fea7.png)

This has been reproducible in support using the Safari browser. For those impacted the below workaround can be applied, preferably to a custom plugin or a child themes CSS:

```css
[amp] .wp-block-image .aligncenter,
[amp] .wp-block-image .aligncenter > figcaption {
    position:relative;
    display:inline-block;
}
```

## Steps to reproduce

1. Add an image with a caption using the default WordPress editor (not classic)
2. Set the image alignment to center
3. With the captions from a Safari device

The impacted user kindly provided raw code which can be inserted to replicate this behavior

`<figure class="wp-block-image size-large"><img src="https://undiscoveredberchtesgaden.com/wp-content/uploads/2021/03/Lake-Konigssee-Echowand.jpg" alt="" /><figcaption>Despite the introduction of electric boats in the early 20th century to minimise noise pollution, the use of the black powder pistols continued up until the 1930s</figcaption></figure>`

`<div class="wp-block-image"><figure class="aligncenter size-large"><img src="https://undiscoveredberchtesgaden.com/wp-content/uploads/2021/03/Lake-Konigssee-Echowand.jpg" alt="" /><figcaption>Despite the introduction of electric boats in the early 20th century to minimise noise pollution, the use of the black powder pistols continued up until the 1930s</figcaption></figure></div>. `

## Additional context

 - WordPress version: 5..7
 - Plugin version: AMP Plugin v2.0.11 
 - Site Health [information provided](https://docs.google.com/forms/d/1JTQmphDlk9YgHpDoFRbHXpkDqv8-QmzTT7MDR4AstyQ/edit#response=ACYDBNhw3qJSyBezcKLwmwRvdG86aEjuDuPmYvCOAfaq3oBEQxm5tt1Tn0S-lVjKkL1Dsts), nothing obvious stands out
 - AMP plugin template mode: standard
 - Browser: Safari
 - Issue doesn't occur in canonical URLs (once switched to transitional mode)
 - Occurs across all themes tested, including Twenty Twenty & Twenty Twenty One
 - User tested while all other plugins were deactivated
 - Reproducible in support (Milind using native Safari - in built responsive testing)
 - Occurs on mobile in most cases, although it can occur with the admin toolbar enabled 
 - Occurs on first load only, reloading the same page the issue no longer appears. Alternative changing the device from portrait to landscape the issue is no longer apparent

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment] 2021-04-08 01:15
I just tried reproducing this in Safari for Mac in responsive design mode and I wasn't able to. I also checked in iOS Simulator and didn't see any issue: 

![image](https://user-images.githubusercontent.com/134745/113953606-0bfaae80-97cd-11eb-8bdb-5b15c88803c1.png)

The workaround CSS hasn't been added to the page either as I can see.

**Comment by jamesozzie** [comment] 2021-04-08 18:12
Various tests performed via Browserstack and also using Chromes dev tools emulator. So far unable to view the same issue on the [users site](https://recordit.co/RWfnQdTfAo) and with image block and YouTube clock captions added on a test site. 

@milindmore22 Can you also take a look from your side.

**Comment by milindmore22** [comment] 2021-04-08 18:52
The issue can be seen on the page below with an image having caption and center alignment.
https://plugins.dev6.rt.gw/2021/04/images-with-caption/

OS: Mac OS Catalina 10.15.7 (19H524)
Safari : Version 14.0.3 (15610.4.3.1.6, 15610)

Step to reproduce : 
1) Add image with a caption using GB block editor
2) Change alignment to center 
3) Visit Safari
4) Enter AMP Page URL
5) Develop -> Enter responsive mode.
6) Develop -> Clear Cache
7) Reload

As mentioned earlier it can be seen only in the initial page load (After clearing browser cache  )

here is a screengrab for the same. https://recordit.co/jwGniP8oP1

**Comment by westonruter** [comment] 2021-04-09 02:36
This seems like a Webkit rendering bug, as the issue goes away once the window is resized:

https://user-images.githubusercontent.com/134745/114120538-87c62b00-98a1-11eb-966b-0c745b21512f.mov

**Comment by dkoo** [comment] 2021-06-23 21:14
Just wanted to add that this issue is reproducible after the first page load if you hard refresh (hold shift + refresh).

EDIT TO ADD: This appears to be caused by the use of `display: table-caption` in [WP core styles](https://github.com/WordPress/WordPress/blob/master/wp-includes/blocks/image/style.css#L94). It therefore affects any `figcaption` inside an image block with any alignment class. The following CSS seems to fix the issue for all alignments:

```
.wp-block-image [class^='align'] > figcaption {
	display: block;
}
```

**Comment by lucidgen** [comment] 2021-08-03 07:28
.wp-block-image [class^='align'] > figcaption {
	display: block;
}
Work for me, thank you @dkoo

**Comment by jamesozzie** [comment] 2021-08-04 17:57
@westonruter Do you think there is any action required here or will we close out this one, given it would require a browser specific solution?

**Comment by westonruter** [comment] 2021-08-04 19:19
I bet the problem has to do with the conversion to `amp-img` which then requires the image to have `display:inline-block` instead of `display:inline`, which somehow impacts Safari's rendering. Given that `amp-img` is going to be deprecated in favor of the native `img` (https://github.com/ampproject/amphtml/issues/30442), the AMP plugin will discontinue doing this conversion and the issue could be fixed as a byproduct of that.

**Comment by westonruter** [comment] 2022-07-26 21:33
You can now opt for native `img` in the Advanced settings of the plugin.

**Closed as not planned by westonruter** 2022-07-26 21:33 UTC
Labels: Bug
