### ISSUE TITLE
WordPress gallery

### ISSUE THREAD

**Issue by michaelvdberg** [Automattic/amp-wp#420] opened 2016-07-17 10:42 UTC
I don't know if it's already solved but I got the following problem. I have create a WordPress gallery (article --> Insert media --> create a new gallery). When I look at the AMP version of my website, I see only the first image and not the full gallery.

Does anybody know how I can resolve this problem or how I can create a gallery in the AMP area?

Thanks in advance!

**Comment by amedina** [comment] 2017-07-04 20:27
This is working now; cannot reproduce. Closing for now; please reopen if still experiencing the issue.

**Closed by amedina** 2017-07-04 20:27 UTC
