### ISSUE TITLE
get( 'post_amp_content' ) encodes carriage returns

### ISSUE THREAD

**Issue by iseulde** [Automattic/amp-wp#262] opened 2016-02-24 22:42 UTC
Somehow all carriage returns in the post content are encoded (`&#13;`) where they would not be using `the_content()`. This may cause margins to not collapse properly. I'll try to take a deeper look into this. I don't see this happening on some other sites using this plugin.

**Comment by mjangda** [comment] 2016-02-24 23:22
That's odd. Is `wpautop` disabled on the site?

**Comment by iseulde** [comment] 2016-02-24 23:22
Yes!

**Comment by amedina** [comment] 2017-07-04 20:05
Not able to reproduce this issue.  Closing for now. Reopen if needed.

**Closed by amedina** 2017-07-04 20:05 UTC
