### ISSUE TITLE
Incorrect formating: Generates closing tag for <br> tag

### ISSUE THREAD

**Issue by StarWar** [Automattic/amp-wp#448] opened 2016-08-23 10:26 UTC
I've enabled amp plugin by wordpress and it generates closing tag for <br> tags whenever a br tags is found. <br></br>
I makes the content unreadable. How do I solve this issue. There is no option to customize it. Styling can't solve it. We use html5 and I think it's not needed to use <br/> and this causes issue with amp and it creates `<br></br>` pair which causes double linebreak in browser and makes the content unreadable.

Thanks,

**Comment by mjangda** [comment] 2016-08-23 16:52
Thanks for the report. This is a duplicate of #218.

**Closed by mjangda** 2016-08-23 16:52 UTC
