### ISSUE TITLE
Revisit aligned images with inline width larger than max getting displayed off-center

### ISSUE THREAD

**Issue by westonruter** [Automattic/amp-wp#1086] opened 2018-04-19 23:40 UTC
**As a user, I expect my images inside a post to be aligned correctly, even if they are larger than the `max-width` of the given viewport.**
- [x] AC1: Identify when and why the viewport breaks.
- [x] AC2: A user who has a wider-than-viewport image expects their image to display in margin; using the plugin's sanitizer, we expect this to be fixed automatically. 

---

The conversion of `width` to `max-width` was originally added in #495. This was removed recently in #1064 as it was not determined to be the best solution to the problem reported in #494 (“Aligned images with inline width larger than max get displayed off-center”)? In #610 it was suggested to be removed:

> Notably, the current AMP spec does not […] specify that width should be replaced by max-width, thus these rules are no longer enforced.

It feels like it fixes a symptom but isn't the right solution to the underlying problem. 

In https://github.com/Automattic/amp-wp/pull/1064#issuecomment-382826877 @mehigh comments:

> Instead of replacing the width by max-width, a solution used almost everywhere on the internets is to introduce a max-width: 100%; on the images. That way they would 'stay put' regardless on whether the width attribute is larger than the container or not. But there are edge cases, and nuances, as with any solutions.

So we need to (1) replicate the original issue and (2) determine what the best fix is.

**Comment by postphotos** [comment] 2018-07-18 14:50
Hi @westonruter - I've added a user story and ACs here.

**Comment by hellofromtonya** [comment] 2018-07-24 17:10
## Possible Solution

Going deeper into the discussion above, Gutenberg adds the `width: fit-content;` as it's default width for the `.wp-block-image` attribute, [as found here in the SCSS file](https://github.com/WordPress/gutenberg/blob/6edaf6803e80fc5a0fa043a41e428fa0f113b9c3/core-blocks/image/style.scss#L2).   Notice that the width switches to `min-content` if it includes the class attribute of `is-resized`.

This means we can add a method into the `AMP_Img_Sanitizer` to decide if we should add an inline width.  Here is the decision tree, for which each must be a `true` decision:

- `$node->parentNode` is an instance of `DOMElement`
- `$node->parentNode->tagName` is '`figure'`. 
- it has a `'wp-block-image'` class attribute.
- it does not have a `'is-resized'` class attribute. 

If all of those decisions are `true`, then we can add an inline style `width: auto;`.  That will override the default `fit-content` and achieve our goal of scaling wider images to fit within the content.

**Comment by westonruter** [comment] 2018-07-24 23:58
This seems closely related to #1237, but maybe not. In that ticket, I think the problem is that `amp-img` does not support `object-fit`. In this ticket, is it related in that `fit-content` width is not compatible with `amp-img` like it is with `img`?

**Comment by hellofromtonya** [comment] 2018-07-25 00:04
@westonruter This issue is not linked to a particular theme.  Rather, it's because AMP inserts an inline CSS width rule.  With the `fit-content` with on the `<figure>`, its child node is then set to the width of the image.  When that happens to be larger than the content's width, it will overflow.  Why?  Because `fit-content` automatically scales up to fit its content.

**Comment by hellofromtonya** [comment] 2018-07-25 00:08
@westonruter Issue #1237 appears to be linked to only Twenty Seventeen. This issue is not linked to a particular theme.  

It's a combination of the `<figure>` parent's width being set to `width: fit-content` and `<amp-img>` having an inline CSS width rule added by AMP.  With `fit-content`, it will scale up to the width of its child node.  When that width is larger than the content, it overflows.

**Comment by hellofromtonya** [comment] 2018-07-25 16:31
Upon further exploration, the AMP `<amp-img>` is overflowing the content area when its parent has a width of `fit-content` and the image is wider than the content area.  However, the `<img>` in a non-AMP mode does not overflow with _the same parent and image attribute values_.  

There is a systematic issue in the AMP rendering that appears to be causing the overflow.

PR #1281 fixes the rendering; however, it feels more like a bandaid than a solution.  For now, this PR is put on hold until we can get an answer back from the AMPHTML project.

I've [opened issue ampproject/amphtml/17084](https://github.com/ampproject/amphtml/issues/17084) to capture the issue and its behavior.  This issue may be linked to issue #1237 and its open ticket [ampproject/amphtml/17053](https://github.com/ampproject/amphtml/issues/17053).

**Comment by hellofromtonya** [comment] 2018-08-07 15:55
PR #1281 fixes this issue.  However, it's a potentially a bandaid.  We'll keep this ticket open to track progress on the AMPHTML ticket [ampproject/amphtml/17053](https://github.com/ampproject/amphtml/issues/17053).  Once that ticket is resolved, we can then check for impact or regression issues to our ticket 1086.

**Comment by kienstra** [comment] 2018-09-27 16:58
It looks like this isn't yet fixed in https://github.com/ampproject/amphtml/issues/17053. So I'll move this issue to 'Ready For Merging' soon, as it looks like it will be part of RC1.

**Comment by kienstra** [comment] 2018-10-03 17:34
**Moving To 'Ready For Merging'**

This will be part of the RC1 release, as it looks like the underlying issue is not yet fixed in https://github.com/ampproject/amphtml/issues/17053.

**Comment by kienstra** [comment] 2018-12-04 17:55
**Removing From Milestone**

If it's alright, I'm removing this from the `v1.0` milestone. This issue is really to track https://github.com/ampproject/amphtml/issues/17053, it doesn't require action unless that issue is fixed.

**Closed** 2018-12-04 22:08 UTC
Labels: css, release

**Comment by westonruter** [comment] 2019-03-29 04:05
This is being revisited in #2036. Please test.
