### ISSUE TITLE
</br> automatically added after <br>

### ISSUE THREAD

**Issue by fenecilla** [Automattic/amp-wp#245] opened 2016-02-24 05:37 UTC
When AMP is turned on, &lt;/br&gt; is automatically added after every &lt;br&gt;, which disrupts the display style.
How can I customize AMP so that it does not add &lt;/br&gt; after each &lt;br&gt;.

**Comment by mjangda** [comment] 2016-02-24 05:43
Thanks for the report. I'm going to close this as it's a duplicate of #218.

**Closed by mjangda** 2016-02-24 05:43 UTC
