### ISSUE TITLE
The AMP plugin try generate the Attachament Photos at AMP valid page, this cause a Error 404 in crawl for Google

### ISSUE THREAD

**Issue by robertoaleman** [Automattic/amp-wp#616] opened 2017-01-23 23:44 UTC
How do we reproduce the issue?

Example:

without AMP
http://www.notiactual.com/comer-piedras-gaceta-decreto-reserva-50-la-produccion-agricola-los-clap/gaceta-oficial-41005-1/

with AMP, error 404
http://www.notiactual.com/comer-piedras-gaceta-decreto-reserva-50-la-produccion-agricola-los-clap/gaceta-oficial-41005-1/amp/

without AMP
http://www.notiactual.com/comer-piedras-gaceta-decreto-reserva-50-la-produccion-agricola-los-clap/

with AMP, no error 404
http://www.notiactual.com/comer-piedras-gaceta-decreto-reserva-50-la-produccion-agricola-los-clap/amp/

I thinkered that the additional plugin generate this issue ( AMP for WP - Accelerated Mobile Pages for WordPress), but I deactived, and show the same error..

AMP plugin for Automattic ,do not must crawl the photos to try build valid AMP page with one photo
What browsers are affected?

All
Which AMP version is affected?

Versión 0.4.2 Por Automattic

**Comment by amedina** [comment] 2017-07-06 01:05
Not clear what the issue is; it does not seem to be an issue with the plugin itself. Closing for now. Please reopen if still experiencing the issue.

**Closed by amedina** 2017-07-06 01:05 UTC
