### ISSUE TITLE
A late amphtml URL filter so we can filter the AMP URL

### ISSUE THREAD

**Issue by rhyswynne** [Automattic/amp-wp#5426] opened 2020-09-24 09:45 UTC
## Feature description

We run a blog over a reverse proxy and it is hosted at /blog/. The problem is that the REQUEST_URI that runs in `amp_get_current_url` returns just /post-name/, rather than /blog/post-name/, so the AMP URL is returning as domain.com/blog/post-name/, which causes 404 errors.

We've created a function that replaces the add_amphtml_link with our own custom version, and before the `printf( '<link rel="amphtml" href="%s">', esc_url( $amp_url ) );` it introduces a filter so we can add /blog/ into the amphtml.

It'd be really handy to include something of that ilk in the plugin, so we don't have to maintain two functions.

---------------

_Do not alter or remove anything below. The following sections will be managed by moderators only._

## Acceptance criteria

* 

## Implementation brief

* 

## QA testing instructions

* 

## Demo

* 

## Changelog entry

*

**Comment by westonruter** [comment] 2020-09-24 18:03
This is essentially a duplicate of what we have in progress at https://github.com/ampproject/amp-wp/issues/2204.

But shouldn't you be manipulating `$_SERVER['REQUEST_URI']` to fix it to reflect the path expected for the reverse proxy? Wouldn't that fix the problem?

**Comment by westonruter** [comment] 2020-09-24 18:05
WordPress also makes use of `$_SERVER['REQUEST_URI']` in various places in core (e.g. `redirect_canonical()`), so if you're not doing that replacement globally then other things will break than just AMP.

**Comment by rhyswynne** [comment] 2020-10-05 10:50
Thanks Weston, I've taken that approach instead. If it works better it works better :)

**Closed as completed** 2020-10-05 15:29 UTC
Labels: Support, WS:Core
