### ISSUE TITLE
Youtube Shortcode is not working

### ISSUE THREAD

**Issue by ahmedkaludi** [Automattic/amp-wp#639] opened 2017-02-18 19:20 UTC
For example: [youtube url="https://www.youtube.com/watch?v=JKHtRItE7KM"]
does not display the video

but when I comment out this code from class-amp-youtube-embed.php then it works without validation issue:

```
	function register_embed() {
//		wp_embed_register_handler( 'amp-youtube', self::URL_PATTERN, array( $this, 'oembed' ), -1 );
//		add_shortcode( 'youtube', array( $this, 'shortcode' ) );
	}

	public function unregister_embed() {
//		wp_embed_unregister_handler( 'amp-youtube', -1 );
//		remove_shortcode( 'youtube' );
	}

```

Hope it helps you resolve the issue.

**Comment by mjangda** [comment] 2017-02-18 20:03
What is the Shortcode replaced with in the source of the page? Can you share an example URL where the issue is occurring?

**Comment by amedina** [comment] 2017-06-02 01:21
Closing for now since there is no follow up. Please feel free to re-open if you are still encountering the issue. Thanks for reporting!

**Closed by amedina** 2017-06-02 01:21 UTC
