### ISSUE TITLE
The attribute 'rel' in tag 'a' is set to the invalid value prettyPhoto

### ISSUE THREAD

**Issue by fearles577** [Automattic/amp-wp#351] opened 2016-03-28 06:31 UTC
Hi,

i'm testing this plugin and when i try the validator i have this error for all the images which are set to link to their attachment page :

The attribute 'rel' in tag 'a' is set to the invalid value 'prettyPhoto[rel-1298242505]'
Is this a plugin issue ?

samplepage: http://beykozrc.com/beykoz-rc-off-road-25-12-2015-hidiv-kasri-bulusmasi/amp/#development=1

Thanks..

**Comment by mjangda** [comment] 2016-06-22 21:33
Dupe of #237

**Closed by mjangda** 2016-06-22 21:33 UTC
