### ISSUE TITLE
Blank lines are added when serializing HTML between elements that should not have whitespace

### ISSUE THREAD

**Issue by Frenchomatic** [Automattic/amp-wp#1304] opened 2018-08-01 17:31 UTC
Class AMP_Content_Sanitizer in class-amp-content.php

$content containing `><` from the editor is fine up until where it gets sanitized. At this point a blank line appears to get inserted into $sanitzed_content.   If you trace it through I think there is a problem in class AMP_Content_Sanitizer with this file being called class-amp-dom-utils.php - it is doing something strange. In other words

`<li><strong>` is in $content (the editor) but in $sanitzed_content you get `<li>BLANK LINE<strong>`

Another example 

```
<h2>Blal Bla <span class="green">more text</span></h2> gets rendered as 

<h2>Blal Bla <span class="green">more text</span>
</h2>
```

**Comment by westonruter** [comment] 2018-08-01 23:30
AMP and Genesis are not mutually exclusive. A Genesis theme should be fully compatible with the plugin's [AMP theme support](https://github.com/Automattic/amp-wp/wiki/Adding-Theme-Support), which was introduced in 0.7 and is being improved for the 1.0 release; it is now in [1.0-beta1](https://make.xwp.co/2018/07/06/amp-plugin-release-v1-0-beta1/?amp).

**Comment by Frenchomatic** [comment] 2018-08-01 23:45
@westonruter sorry - that was probably not called for. What I mean is I don't get these types of issues with Genesis. If I put something in the editor then that is what I get. If I write bad html I get bad html on the output. If I write good html then I get good html. What we have here is good html being turned into broken html (which ever way you look at it). It effects this plugin and another I use - https://wordpress.org/plugins/accelerated-mobile-pages/ . My PHP skills are not good enough to fix it. Putting $sanitized_content through a minimization function helps but I still I have lists using `<li><strong>` and it just turns a blank line into a space i.e.  list items don't line up.

**Comment by westonruter** [comment] 2018-08-01 23:52
I understand. And it is a bug, as you've identified. So we'll try to fix it. It's difficult because it doesn't seem to be a PHP coding issue at all but a lower-level libxml issue.

**Comment by Frenchomatic** [comment] 2018-08-01 23:55
thanks @westonruter - I thought it may just be me because I have been banging on about it with the other plugin developer but not had great responses. I now understand that it is probably beyond them too.

**Comment by westonruter** [comment] 2018-08-02 00:18
I can see that the issue is fixed in PHP 7.3 which is nearing release: https://3v4l.org/dY39m

![image](https://user-images.githubusercontent.com/134745/43555422-d5668236-95ae-11e8-9db5-a50e78313ea3.png)

**Comment by westonruter** [comment] 2018-08-02 22:02
@Frenchomatic please test https://github.com/Automattic/amp-wp/pull/1309#issuecomment-410081948

**Closed** 2018-08-03 01:55 UTC
Labels: [Type] Bug

**Comment by Frenchomatic** [comment] 2018-08-03 08:16
@westonruter Lovely so far on my end. Tested a few scenarios - in particular this one `<h2>Bal Bla <span class="something">more text</span></h2>` now renders as it should.
