### ISSUE TITLE
AMP Conversions Not Activated When URL Contains '/video/'

### ISSUE THREAD

**Issue by gunawantacc** [Automattic/amp-wp#7863] opened 2024-08-20 11:12 UTC
### Bug Description

Please address the issue where AMP conversions are not activated when URLs contain '/video/'.

I initially discovered this issue while rewriting and redirecting video media attachment pages within the '/video/' structure. The findings are as follows:

- URLs containing '/video/' stop AMP conversions for video content.
- URLs containing '/image/' do not have any issues.
- Changing the base URL to anything other than '/video/', such as '/vid/', solves the issue.

Here is the code snippet that demonstrates the issue:
```
add_filter('attachment_link', function($link, $post_id) {
	$post = get_post($post_id);

	if ($post->post_type == 'attachment') {
		$mime = get_post_mime_type($post_id);

		if (strpos($mime, 'video') !== false) {
			$link = home_url('/video/' . $post->post_name . '/');
		} elseif (strpos($mime, 'image') !== false) {
			$link = home_url('/image/' . $post->post_name . '/');
		}
	}

	return $link;
}, 10, 2);
```

Further testing revealed that simply setting the **permalink structure** (from the WordPress menu, for all posts) to **‘/video/%postname%/’** halts all AMP conversions.

I am currently using Version 2.5.4, the latest available version.

### Expected Behaviour

Posts within the '/video/' URL structure are converted to AMP.

### Screenshots

```
<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />
    <title>...</title>
    ...
    <!-- No AMP scripts embedded by the plugin -->
    ...
    <meta name="generator" content="AMP Plugin v2.5.4; mode=standard">
</head>
<body>
    ...
</body>
</html>
```

### PHP Version

7.4

### Plugin Version

2.5.4

### AMP plugin template mode

Standard

### WordPress Version

6.6.1

**Comment by westonruter** [comment] 2024-08-20 20:33
@milindmore22 Are you able to reproduce this?

**Comment by westonruter** [comment] 2024-08-20 20:34
Oh, I see this is a duplicate of a [support topic](https://wordpress.org/support/topic/bug-report-amp-conversions-not-activated-when-url-contains-video/). Closing in favor of the support forum.

**Closed as not planned by westonruter** 2024-08-20 20:34 UTC
Labels: Bug, Duplicate
