### ISSUE TITLE
Playbuzz not working in 0.5.1

### ISSUE THREAD

**Issue by amedina** [Automattic/amp-wp#761] opened 2017-08-17 20:52 UTC
http://www.playbuzz.com/

**Comment by amedina** [comment] 2017-08-17 20:52
Related to: https://github.com/Automattic/amp-wp/issues/760

**Comment by brunomosciatti** [comment] 2017-08-17 20:57
On WP we insert the playbuzz tag like this:
[playbuzz-item item="id-from-the-content-here" format="story"]

and the tag for playbuzz is:

<amp-playbuzz
	    src="id-from-the-content-here"
	    height="500"
	    data-item-info="true"
	    data-share-buttons="true"
	    data-comments="true">
	</amp-playbuzz>
I need to when inserted the playbuzz-item in wordpress, automatically insert the id of this content into the "src" of

**Comment by lysk88** [comment] 2017-08-18 11:56
@amedina  hey, playbuzz items should be supported, its already merged into the master and went live with version 0.5 (see change log).
however, i'm experience issues with last the update ( version 0.5.1) when the the amp-playbuzz component seems to be stripped out.

**Comment by brunomosciatti** [comment] 2017-08-18 12:05
hey @lysk88 , I saw your name on changelog :D 

so are you saying that this issue was solved with version 0.5? How can I do it?

thanks

**Comment by lysk88** [comment] 2017-08-18 12:11
@brunomosciatti  
seems like amp-playbuzz not working well with version 0.5.1.
I will open a new issue to handle this from there. 

meanwhile , you can try to install version 0.5, amp-playbuzz should working fine with that version.  you can download it from here [https://wordpress.org/plugins/amp/advanced/](url)

**Comment by brunomosciatti** [comment] 2017-08-18 12:13
@lysk88 got 404 for this url :/

I can install version 0.5 but how the amp-playbuzz works? Its auto generated?

> >>The playbuzz amp tag is auto generated by the main (wordpress) tag?

**Comment by lysk88** [comment] 2017-08-18 12:16
yes.

**Comment by brunomosciatti** [comment] 2017-08-18 13:24
thanks a lot @lysk88 ! it really works on 0.5

**Comment by amedina** [comment] 2017-08-18 16:28
Hi guys, my bad. Looking into it.

**Comment by amedina** [comment] 2017-08-18 16:38
HI @lysk88, @brunomosciatti My bad; looking into it.

**Comment by amedina** [comment] 2017-08-18 17:05
@lysk88, @brunomosciatti Could you share some of the shortcodes you are using to test? (if they are public stories)

**Comment by lysk88** [comment] 2017-08-18 17:17
sure, try this 
`[playbuzz-item item="022092ce-8a99-48ab-aa5a-a40517c77074" format="list"]`

**Comment by amedina** [comment] 2017-08-18 23:05
@lysk88,  Are you using another plugin such as [this one]( https://en-ca.wordpress.org/plugins/playbuzz/)?

Playbuzz is not "directly" supported by the plugin in the sense that there is not an embed handler for it; instead, the plugin transcodes a Playbuzz embed placed in the post via other means (e.g. another plugin) into an amp-playbuzz component. Want to determine how is the playbuzz shortcode  transcoded into an playbuzz embed first, before it is handled by the AMP plugin.

**Comment by lysk88** [comment] 2017-08-19 16:09
sorry, i think i confused you. 
 this -> `[playbuzz-item item="022092ce-8a99-48ab-aa5a-a40517c77074" format="list"]`
is playbuzz shortcode that can be transcoded to playbuzz embed code  -> 
`<script type="text/javascript" src="//cdn.playbuzz.com/widget/feed.js"></script>
<div class="pb_feed" data-embed-by="64fc80bf-6235-4325-9068-9c7eb32714b2" data-item="022092ce-8a99-48ab-aa5a-a40517c77074"  ></div>`
via the plugin you mentioned above. 

amp plugin looking for playbuzz embed code then transcoded it to amp-playbuzz.

**Comment by moisespr** [comment] 2017-08-26 12:34
Hi guys, I have this in Search Console for several AMP with playbuzz:
"The extension 'amp-playbuzz' was found on this page, but is unused."

I found out that 'src' is a required attribute, but amp-playbuzz supports either 'src' or 'data-item'. As a quick workaround I'm inserting an empty 'src' attribute in AMP_Playbuzz_Sanitizer when 'data-item' is found.

Looking forward for a real fix.

Thanks

**Comment by moisespr** [comment] 2017-08-26 12:58
My workaround doesn't work, not I"m getting: Mutually exclusive attributes encountered in tag 'amp-playbuzz' - pick one of ['src', 'data-item'].

**Comment by alongendler** [comment] 2017-08-27 12:47
Hey @amedina,
Do you have any news? can i help in someway?

**Comment by amedina** [comment] 2017-08-28 20:45
@alongendler Unfortunately I haven't had time to dig into this at all :( We will as soon as we can.  If you have a proposed solution please submit a PR.

**Comment by brunomosciatti** [comment] 2017-08-31 12:11
Hey guys, after updating my plugin Im with some issues according to Google Search Console.

AMP Page for example: https://todateen.com.br/anitta-dj-alok-produzindo-parceria/amp/

The Amp Validator (https://validator.ampproject.org/) says that is a <script> tag not allowed

Printscreen: https://sketch.io/render/sk-974a93e9b0d78d4a3ac7bc2e9a57ba73.jpeg

**Comment by brunomosciatti** [comment] 2017-10-04 12:16
@moisespr how did u solve "The extension 'amp-playbuzz' was found on this page, but is unused. Please remove this extension." ?

**Comment by harrisdavid** [comment] 2017-12-07 14:14
The issue is in /includes/sanitizers/class-amp-allowed-tags-generated.php
In the Playbuzz definitions (arround line 1200) the "attr_spec_list" has "src" incorrectly set as a mandatory field. 
As far as I can tell you could use src or (more commonly and used by the WP Playbuzz plugin) data-item to get valid playbuzz items.
Commmenting out the 'mandatory' => true gets the tags working as they should (but without the validation.

**Closed** 2017-12-12 06:03 UTC
Labels: [Priority] Medium, [Type] Bug
